Enable content copying transitive in VS.
dotnet/sdk pull request #11254
Opened 2020-04-11 19:59 UTC by ocallesp

This is needed to fix the Fast up-to-date to check
CopyToOutputDirectory items from project references
https://github.com/dotnet/project-system/issues/4665

More details on MSBuildCopyContentTransitively in
https://github.com/microsoft/msbuild/pull/4865

Is there a way to create a dummy insertion to test it out first ? to check the performance test from AzDo

2020-04-14 21:00 UTC, wli3 commented
We don't have a VS branch for master yet. Talked to @ocallesp offline, this is not urgent. So let's wait until there is a VS branch then check it in (maybe several months) -- we don't have a good way to make dummy VS insertion in order to run perf test. So by then we would make a real core-sdk build with this change. If it is rejected by VS test, we should revert it.

2020-04-14 21:06 UTC, wli3 commented
Also I am not sure a property in **publish**.target will affect design time build. Please double check the fix

2020-04-14 21:07 UTC, wli3 requested changes
per comment

2020-04-15 08:30 UTC, donJoseLuis approved these changes

2020-04-29 21:55 UTC, wli3 commented
@ocallesp any update on this?

2020-05-06 21:27 UTC, wli3 commented
@ocallesp please reopen you are back on this task

2020-05-06 21:27 UTC, closed without merging