Fix transitive content conflicts Fixes #3871
dotnet/sdk pull request #11352
Opened 2020-04-20 18:53 UTC by Forgind

Changes this to opt-out for sdk-style projects. (See discussion in [microsoft/msbuild#4931](https://github.com/microsoft/msbuild/pull/4931) and [microsoft/msbuild#4997](https://github.com/microsoft/msbuild/pull/4997).)

Fixes #3871.

2020-04-20 23:15 UTC, sfoslund approved these changes

2020-04-22 20:09 UTC, dsplaisted commented
This also fixes #3864, correct?

2020-04-22 22:09 UTC, sfoslund commented
@dsplaisted I don't think so, this ensures that transitive content files don't overwrite other content files of the same name. If I'm reading #3864 correctly, that issue refers to copying all transitive content, regardless of name.

2020-04-27 17:04 UTC, sfoslund requested changes

2020-04-27 17:04 UTC, sfoslund commented on src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
> +    <CopyConflictingTransitiveContent>true</CopyConflictingTransitiveContent>
I think this needs to be switched to false, per https://github.com/microsoft/msbuild/pull/4931#discussion_r415856633

2020-04-27 17:15 UTC, Forgind commented on src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.props
> +    <CopyConflictingTransitiveContent>true</CopyConflictingTransitiveContent>
```suggestion
    <CopyConflictingTransitiveContent>false</CopyConflictingTransitiveContent>
```

2020-04-27 17:17 UTC, sfoslund approved these changes

2020-05-04 20:13 UTC, sfoslund commented
@Forgind @dsplaisted the corresponding MSBuild PR was merged, right? So this can be merged too?

2020-05-04 20:22 UTC, Forgind commented
Can confirm:
https://github.com/microsoft/msbuild/pull/4931

2020-05-05 15:38 UTC, sfoslund commented
@Forgind cool, I'm merging with master to get the new version of MSBuild that has the change, just to get CI run with it enabled.

2020-05-05 15:45 UTC, rainersigwald commented
Should this have a test and an inverse test for when it's explicitly disabled?

2020-05-05 20:43 UTC, sfoslund commented
@rainersigwald sure, I just pushed the test I wrote back in November 😆. It's a little messy because this issue is hard to repro/ detect consistently.

2020-05-06 16:42 UTC, sfoslund commented
Weird, this tests is reliable on my local machine but it looks like it's really flaky in general. @Forgind were you able to get a consistent repro when you were testing that could be put into this testing format?

2020-05-07 18:45 UTC, Forgind commented
It seemed to repro reasonably consistently if I remember correctly, but I just manually tested it, and unfortunately, this isn't very high on my priority list right now. I can try to get back to it in another month or so.

2020-05-08 22:08 UTC, sfoslund commented
I've added a new test that asserts the target output instead of the file that ends up in the output folder, which is unreliable when there are conflicting content files. This one should be much more reliable and doesn't require adding a new test asset.

@dsplaisted can you review, since I've added code?

2020-05-08 22:18 UTC, dsplaisted approved these changes

2020-05-08 22:18 UTC, dsplaisted commented on src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
> +        public void It_disables_copying_conflicting_transitive_content(bool copyConflictingTransitiveContent)
Should we also cover the case where the property is implicitly vs explicitly set to false?

2020-05-08 22:18 UTC, dsplaisted commented on src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
> +                String.Join(';',valuesResult).Should().Contain(parentProject.Name);
Both of these assertions are the same.  Was one of them supposed to check for `childProject.Name`?

Also, if so, I think you can write it more simply like this (the syntax may be slightly off):

```c#
valuesResult.Should().BeEquivalentTo(parentProject.Name, childProject.Name);
```

2020-05-08 22:18 UTC, dsplaisted commented on src/Tests/Microsoft.NET.Build.Tests/GivenThatWeWantToReferenceAProject.cs
> +                var projRef = new XElement(ns + "ProjectReference",
You can add a project reference via the `ReferencedProjects` property of `TestProject` instead of manipulating the XML as done here.

2020-05-12 14:54 UTC, merged