Check the targetext to determine if a framework project can be run on F5
dotnet/sdk pull request #1176
Opened 2017-05-03 23:25 UTC by basoundr

We should be able to run both Console Application and Windows Application on F5 for Framework Projects

This is to address the issue project-system/2033

Tagging @dotnet/project-system @srivatsn @davkean for review

2017-05-03 23:25 UTC, basoundr commented
Opened #1175 to target post preview 1

2017-05-04 04:17 UTC, nguerrera commented
Please keep just one copy open until we sort out the right changes and then port to the other branch.

2017-05-04 04:18 UTC, nguerrera requested changes
See above

2017-05-04 18:31 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.targets
> +    <When Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework' and '$(TargetExt)' == '.exe'">
Another note: WinExe support on core may be coming soon: dotnet/core-setup#196

2017-05-04 18:58 UTC, nguerrera commented
Closing in favor of #1178

2017-05-04 18:58 UTC, closed without merging