Compose ASPNETCORE_HOSTINGSTARTUPASSEMBLIES if present in launchSettings.json
dotnet/sdk pull request #12604
Opened 2020-07-23 01:11 UTC by pranavkm

2020-07-24 20:53 UTC, wli3 requested changes

2020-07-24 20:53 UTC, wli3 commented on src/Tests/dotnet-run.Tests/GivenDotnetRunRunsCsProj.cs
> +               .WithEnvironmentVariable("ASPNETCORE_HOSTINGSTARTUPASSEMBLIES", "HostingStartupAmbient")
You are testing if `HostingStartupInLaunchSettings` will be added from `LaunchSettings`? The test name is not very clear.

2020-07-24 20:53 UTC, wli3 commented on src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
> +                        if (entry.Key == "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES")
This is not ideal. SDK is supposed to be neutral. But this is clearly ASPNET specific code. Can it be something generic?

2020-07-24 20:53 UTC, wli3 commented
also could you rebase on to the PR you just merged? So it  is clear to see the new change

2020-07-24 20:55 UTC, wli3 commented
Directly ping me if this PR is urgent (it is near to 5.0 closing time)

2020-07-24 20:58 UTC, wli3 commented on src/Cli/dotnet/commands/dotnet-run/RunCommand.cs
> +                        if (entry.Key == "ASPNETCORE_HOSTINGSTARTUPASSEMBLIES")
Have an abstraction in launchSettings to let a list of entries to be EnvironmentVariables maybe better.

2020-07-24 21:01 UTC, wli3 commented
And can this work in VS at all? Or it is a dotnet-watch specific feature? can it be in dotnet-watch? IE, dotnet-watch to duplicate some of the code for finding the dll to run.

2020-07-27 17:02 UTC, pranavkm commented
Thanks for the feedback Will. I've a couple of p8 issues to get to, I'll try and get to this after.

> And can this work in VS at all?

@vijayrkn \ @BillHiebert ?

This is not a dotnet-watch specific feature. It's a feature of any app launcher that reads launchSettings.json.

2020-08-26 21:13 UTC, marcpopMSFT commented
@pranavkm checking in on when you were going to come back to this. Thanks.

2020-08-26 21:34 UTC, pranavkm commented
There's at least one ASP.NET Core template that isn't going to work with the new features we added to `dotnet watch`, but I'd like better job with this change which I don't have time for at this moment. I'll reopen once I've something I'd like to get in.

2020-08-26 21:34 UTC, closed without merging