Import Framework WinFX Targets By Default Only When Targeting .NETFramework
dotnet/sdk pull request #12764
Opened 2020-08-04 17:24 UTC by BenVillalobos

Should fix https://github.com/dotnet/sdk/issues/12324, though this has not been verified yet. Context is inside the issue.

2020-08-04 18:29 UTC, BenVillalobos commented
https://github.com/dotnet/sdk/issues/12324#issuecomment-668751372

> Doing some quick testing (thanks @Forgind) it doesn't look like that suggestion works @dsplaisted . I'm thinking at this point we make this opt-in instead of opt-out. So if `ImportWinFXTargets` isn't set, SDK sets it to true by default. This reverts to functionality before the [original issue](https://github.com/dotnet/msbuild/issues/4948) and provides a workaround for those that run into that. How does this sound?
> 
> An interesting observation is that when we force `ImportFrameworkWinFXTargets` to true, we get a different issue in [this repro](https://github.com/dotnet/sdk/issues/12739). @davkean is this something you've seen before? This error happens on 16.8.0 Preview 2.0 [30404.33.master]. It looks unrelated to project system since it works in 16.6.5.
> 
> Error:
> 
> ```
> C:\Users\namytelk\Documents\GitHub\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS
> \Waiting\VisualStudioWaitIndicator.cs(101,24): error CS8619: Nullability of reference types in value of type '(WaitInd
> icatorResult Canceled, T?)' doesn't match target type '(WaitIndicatorResult, T)'. [C:\Users\namytelk\Documents\GitHub\
> project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS_q44
> qb5gw_wpftmp.csproj]
> C:\Users\namytelk\Documents\GitHub\project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\ProjectSystem\VS
> \Waiting\VisualStudioWaitIndicator.cs(108,24): error CS8619: Nullability of reference types in value of type '(WaitInd
> icatorResult Canceled, T?)' doesn't match target type '(WaitIndicatorResult, T)'. [C:\Users\namytelk\Documents\GitHub\
> project-system\src\Microsoft.VisualStudio.ProjectSystem.Managed.VS\Microsoft.VisualStudio.ProjectSystem.Managed.VS_q44
> qb5gw_wpftmp.csproj]
> ```

2020-08-05 00:07 UTC, dsplaisted requested changes
I do not think we should ever import these by default if targeting .NET Core.  If I'm understanding the regressions correctly, they are all for projects that target .NET Framework.  Does that make sense?

2020-08-05 03:13 UTC, merged

2020-08-05 05:28 UTC, Nirmal4G commented
@BenVillalobos This is already allowing opt-out. This is an unneeded change in the SDK as it is covered by msbuild#5425

Having this specified in multiple places creates consfusion and more regressions. I propose we move them to msbuild and the desktop sdk alone.

@dsplaisted @rainersigwald Can we reopen and discuss this?

2020-08-05 06:12 UTC, Nirmal4G commented
@BenVillalobos This is already allowing opt-out. We could remove the entire section in the SDK and replace it with changes from dotnet/msbuild#5425 and dotnet/wpf#2976. This will surely fix a host of problems down the road.

Having this specified in multiple places creates confusion and more regressions. I propose we move them to MSBuild and the Desktop SDK targets (i.e. near to where the WinFX targets are actually imported).

@dsplaisted @rainersigwald Can we reopen and discuss this?

2020-08-05 08:46 UTC, chucker commented
>I propose we move them to MSBuild and the Desktop SDK targets (i.e. near to where the WinFX targets are actually imported).

Unless I'm missing something: the Desktop SDK targets are for using WinFX (WPF) on top of .NET Core / .NET 5. This issue, however, affects apps that are on .NET _Framework_, but use Sdk-style projects, e.g. with the `MSBuild.Sdk.Extras` SDK, _not_ the `WindowsDesktop` one.

2020-08-05 09:21 UTC, Nirmal4G commented
> Unless I'm missing something

The .NET SDK Extras already uses Desktop SDK props/targets if it is present. So, it'll be a cascading effect, if we fix them in MSBuild/WindowsDesktop SDKs.

2020-08-07 06:09 UTC, dsplaisted commented
#12786 updates the logic from this PR.