Implement workload suggestion API
dotnet/sdk pull request #13719
Opened 2020-09-21 06:25 UTC by mhutch

Adds an API to suggest which workloads should be installed to satisfy a set of missing workload packs.

Fixes the NotImplementException in the workload manifest reader library.

2020-09-21 20:40 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
> +            var scoredList = completeCandidates.Select(
nit: use better naming and extract class, extract method to reduce comments.

2020-09-21 20:43 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
> +            //find all valid complete permutations by recursively exploring possible branches from a root
nit: same here.

And a method that worth comments every 3 lines is a dangerous method to edit later. We need more test around this method. And it is better to make it a separate method, even a separate class.

2020-09-21 21:03 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
> +        public ISet<WorkloadInfo> GetWorkloadSuggestionForMissingPacks(IList<string> packIds)
method too long

2020-09-21 21:03 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/IWorkloadResolver.cs
> +        ISet<WorkloadResolver.WorkloadInfo> GetWorkloadSuggestionForMissingPacks(IList<string> packId);
@dsplaisted please check if the API is what you need

2020-09-21 21:13 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
> +                    var satisfied = requestedPacks.Count - stillMissing.Count;
not used variable?

2020-09-21 21:13 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadResolver.cs
> +                    var installedCount = c.Packs.Count(p => installedPacks.Contains(p));
no obvious test for the scores. This part sounds super complex. If a later change messed up the score logic, a test need to fail.

And it is complicated enough that I cannot say it really works by just reading it.

2020-09-30 21:21 UTC, marcpopMSFT commented
Marked for 5.0.2xx.  The branch isn't open yet but retarget once it is in ~1 month.

2020-10-05 22:54 UTC, wli3 requested changes
Still don't have enough test cover GatherCompleteSuggestions

2020-10-05 22:54 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +            public int ExtraPacks { get; internal set; }
> How many additional (and potentionally unnecessary)

I don't understand what that means. The number could be too high due to some of the packs are unnecessary? And I need to read the comments to understand what the property does. It is a complex concept, it is fine to have a longer name.

2020-10-05 22:54 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +        class WorkloadSuggestionCandidate : IEquatable<WorkloadSuggestionCandidate>
nit: please add explicit modifier per editorconfig

2020-10-05 22:54 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +        private T FindBest<T>(IEnumerable<T> values, params Comparison<T>[] comparators)
what's the difference between this and Max() ?

2020-10-05 22:54 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +        class WorkloadSuggestionCandidate : IEquatable<WorkloadSuggestionCandidate>
I have problem understanding what's this class present. It is a collection of Workloads , Packs but  GatherCompleteSuggestions has a list and a set of them (collection of collection of workload?). What does the branch mean here?

2020-10-05 22:54 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +                    hashcode ^= id.GetHashCode();
order matters?

2020-10-05 22:58 UTC, wli3 commented on src/Resolvers/Microsoft.NET.Sdk.WorkloadManifestReader/WorkloadSuggestionFinder.cs
> +            public HashSet<WorkloadDefinitionId> Workloads { get; }
possible to make it immutable?

2020-10-05 23:02 UTC, wli3 commented
I hope to have some test to cover and document GatherCompleteSuggestions. Example of "recursively explores a branching tree". What kind of candidate is not "the best"

2020-11-03 05:23 UTC, wli3 commented
@mhutch could you retarget to release/5.0.2xx? And the logic of union and sort is still hard to understand. We need to have unit tests around it. 1. to document what it does 2. prevent regression and make future change easier, considering it will be someone from SDK team to maintain this code in the long term.

2020-11-10 18:04 UTC, mhutch commented
@wli3 i've retargeted it. could you be more specific about what you want additional tests and documentation on?

2020-11-16 22:08 UTC, wli3 commented
@mhutch sorry for being late. I missed the notification somehow. If we could write unit tests for every major methods in WorkloadSuggestionFinder.cs, it would be great. Like FindBest, FilterRedundantSuggestions,GatherCompleteSuggestions, and the constructor of WorkloadSuggestionFinder.

2020-11-20 01:38 UTC, mhutch commented
@wli3 The constructor was already implicitly covered by `CanSuggestSimpleWorkload`, `CanSuggestTwoWorkloadsToFulfilTwoRequirements` and `CanSuggestWorkloadThatFulfillsTwoRequirements` and I didn't see a clean way to test it by itself, but I factored out a chunk of logic into `FindPartialSuggestionsAndSimpleCompleteSuggestions` and added a test for that and  `GetBestSuggestion`. I also added some more doc comments, tried to clarify naming, and moved the suggestion finder tests to their own class.

2020-12-07 23:35 UTC, wli3 commented
Sorry @mhutch I missed the notification of your changes. Please go ahead to merge it after resolving the merge conflict. I can resolve the conflict and merge it if you need.

2020-12-07 23:35 UTC, wli3 approved these changes

2020-12-10 18:13 UTC, merged