Correctly handle `$(InvariantGlobalization)='false'`
dotnet/sdk pull request #15977
Opened 2021-02-20 03:28 UTC by radical

In `Microsoft.NET.Sdk.targets`:

```xml
     <RuntimeHostConfigurationOption Include="System.Globalization.Invariant"
                                    Condition="'$(InvariantGlobalization)' != ''"
                                     Value="$(InvariantGlobalization)"
                                     Trim="true" />
```

The above is intended to include `System.Globalization.Invariant`, if
`$(InvariantGlobalization)` is false. The default value should be false,
and is treated as such in it's usage.

But the condition here will cause this to be included as long as the
property is non-empty. This manifested in blazorwasm workload testing,
because Blazor wasm targets explicitly set that property to `false`,
which caused the icu bits to be incorrectly linked out.

2021-02-20 03:28 UTC, radical commented
/cc @lewing @vargaz @akoeplinger

2021-02-20 05:41 UTC, vargaz commented
The linking out of icu was correct, only the icu detection code was linked out, since we know its there.
This would be the correct fix imho:
https://github.com/dotnet/runtime/pull/48550

2021-02-20 05:51 UTC, radical commented
@vargaz I think then both are needed. This PR makes the behavior of `InvariantGlobalization=''` same as `InvariantGlobalization=false`. My description is inadequate, IIUC.

2021-02-20 06:12 UTC, vargaz commented
Wouldn't it be better to do:
<InvariantGlobalization Condition="'$(InvariantGlobalization)' == 'true'">false</InvariantGlobalization>
?

2021-02-20 06:16 UTC, radical commented
> Wouldn't it be better to do:
> 
> ```
> <InvariantGlobalization Condition="'$(InvariantGlobalization)' == ''">false</InvariantGlobalization>
> ```
> 
> ?

Sure, but this should still work correctly for `''`, IMHO.

2021-02-20 07:32 UTC, vargaz commented
If we initialize it like all other properties, then the empty case can't happen.

2021-02-20 13:04 UTC, steveisok commented
It should be initialized properly in blazor projects https://github.com/dotnet/sdk/blob/265625feabf81d76a507907fab533b249decda70/src/BlazorWasmSdk/Targets/Microsoft.NET.Sdk.BlazorWebAssembly.Current.targets#L54

If I'm understanding things correctly, I think this PR makes sense.

2021-02-21 05:41 UTC, vargaz commented
The problem is that the wasm targets should initialize it, since they reference it.

2021-02-21 05:45 UTC, radical commented
We can do that in wasm targets. But the condition here would do the wrong thing even when we initialize it to "false", which is what blazor did in fact.

2021-02-21 07:18 UTC, vargaz approved these changes

2021-02-22 03:29 UTC, eerhardt requested changes
This is not correct. We want to set the the AppContext switch and the trimming feature switch either way, if the user (or a higher SDK) explicitly sets it to `true` or `false`.

I believe this PR should be closed and not merged. Let me know if you need more explanation.

Also see the description in https://github.com/dotnet/runtime/pull/47999, which shows how much IL savings we get by trimming code when the feature switch is explicitly set to `false`.

2021-02-22 04:11 UTC, radical commented
Looks like I completely misunderstood what that msbuild item was for! IIUC now, that essentially controls the `--feature` flag to be passed to the linker, and so we want to pass on `$(InvariantGlobalizatiton)` value, as long as it's set.

Do I understand correctly that passing `--feature System.Globalization.Invariant false` would be the same as not passing `--feature System.Globalization.Invariant .. ` at all?

So, no change is required here at all. And @vargaz's fix is the only one required.

2021-02-22 15:24 UTC, eerhardt commented
>  that essentially controls the --feature flag to be passed to the linker

It controls 2 things:

1. The `--feature` flag to be passed to the linker. (See https://github.com/dotnet/designs/blob/main/accepted/2020/feature-switch.md for more information)
2. (The original intent of the MSBuild Item) It controls what is written to the `runtimeconfig.json` file. Whether `true` or `false` is explicitly written, or nothing if it isn't set in MSBuild. 

> Do I understand correctly that passing --feature System.Globalization.Invariant false would be the same as not passing --feature System.Globalization.Invariant .. at all?

No, this is not 100% identical. 

1. In this case, even though `false` is the equivalent default, explicitly putting `false` in the `runtimeconfig.json` will make the app behave differently w.r.t. the corresponding environment variable. See [the code here](https://github.com/dotnet/runtime/blob/8a52f1e948b6f22f418817ec1068f07b8dae2aa5/src/libraries/System.Private.CoreLib/src/System/Globalization/GlobalizationMode.cs#L17-L29). If `false` is explicitly set in the `runtimeconfig.json`, the environment variable isn't even read.
2. Passing `--feature System.Globalization.Invariant false` trims out the code that is only needed in the `System.Globalization.Invariant=true` code path. See https://github.com/dotnet/runtime/pull/47999. If the `--feature` flag isn't passed at all, both code paths will exist in IL.

> Sorry about all the confusion!

No worries. We are all here to help.

2021-02-22 22:06 UTC, radical commented
Thanks for the detailed explanations, and links! 👍

2021-02-22 22:06 UTC, closed without merging

2021-02-24 21:54 UTC, vargaz commented
So the InvariantGlobalization variable is not really a boolean ? It has 3 possible values, '', 'false', and 'true' with 3 different behaviors ?

2021-02-25 15:30 UTC, eerhardt commented
The runtime behavior has only 2 possible values - invariant or not.

But with respect to trimming IL, yes it has 3 possible values:

* Trim the IL that has only to do with Invariant = true
* Trim the IL that has only to do with Invariant = false
* Don't trim any IL and leave both paths in the code, it will be decided at runtime which path to take