Revert "Update support libraries to those that are only lib."
dotnet/sdk pull request #1610
Opened 2017-09-26 22:13 UTC by dsplaisted

Reverts dotnet/sdk#1582, which broke ASP.NET Core web apps running on .NET Framework.

A description of the issue, thanks to @eerhardt:

Previously we used to reference both the “ref assembly” to compile and the “runtime assembly” to run.  Now, we are no longer referencing the “ref assembly” at compile time.  We are compiling and running solely against the “runtime assembly”.

This changed the way the .deps.json file is created.  For the assembly it is looking for “Microsoft.Win32.Primitives”, the deps.json file changed from:

```
"Microsoft.Win32.Primitives/4.0.3.0": {
      "type": "referenceassembly",
```

In the old file to 

```
    "Microsoft.Win32.Primitives/4.0.3.0": {
      "type": "reference",
```

We have a pretty well-known bug in the 2.0.0 version of the DependencyModel library that was fixed in 2.0.1 - https://github.com/dotnet/core-setup/issues/2981.  Basically, the DependencyModel doesn’t resolve “type: reference” libraries correctly.

2017-09-26 22:15 UTC, nguerrera approved these changes

2017-09-26 23:38 UTC, ericstj requested changes
Why revert?  The issue this is fixing is a bigger problem for customers than the regression (a bug in that component) and the regression has a simple workaround.  Moreover I discussed with you a small change to this issue that would not cause the regression.

2017-09-27 00:11 UTC, ericstj approved these changes

2017-09-27 00:15 UTC, dsplaisted commented
@ericstj We basically have to have a build with a fix by tomorrow morning, so reverting the change is less risky than even applying a simple fix.

The bug in DependencyModel (when combined with the fixes in #1582) completely breaks ASP.NET Core web apps running on .NET Framework.

#1582 does have important fixes in it, so we will try to get those fixes together with a workaround for the DependencyModel issue out as soon as possible, hopefully in 15.4.1.

2017-09-27 00:16 UTC, ericstj commented
I am not intending to block this, but I do disaaporove of revert for the reasons mentioned above.  At a minimum I'd like to see you explain how you intend to fix this the right way and a timeline for that.

2017-09-27 00:54 UTC, merged

2017-09-27 14:47 UTC, dsplaisted commented
@ericstj Here's the PR which brings back the fixes: #1612