Simplify the path that dotnet-watch is installed to
dotnet/sdk pull request #16509
Opened 2021-03-25 04:43 UTC by pranavkm

VS attempts to load a couple of binaries carried by dotnet-watch. Currently this involves
digging around a bunch of directories. This simplifies the process a bit for them.

Fixes https://github.com/dotnet/aspnetcore/issues/30860

2021-03-25 04:43 UTC, pranavkm commented on src/Cli/dotnet/CommandFactory/CommandResolution/DotnetToolsCommandResolver.cs
> +            var packagePath = Path.Combine(_dotnetToolPath, arguments.CommandName);
Let me know if there's a better way to approach this

2021-03-25 05:08 UTC, wli3 requested changes
We should not make a special case just for dotnet-watch

2021-03-25 05:15 UTC, wli3 commented
> This simplifies the process a bit for them

But this complicate already complex SDK command resolver logic. I'd rather have the complexity in VS, since it is a special case for dotnet-watch anyway. While resolving "built-in dotnet tools" are not, like `dotnet-dev-cert`, `dotnet-user-secrets`.

Although you could change all of them to an easily predictable location, since it is all from ASPNET now. But you do need to spend more time on dotnet/installer to create the right layout.

2021-03-25 13:54 UTC, pranavkm commented
> Although you could change all of them to an easily predictable location, since they are all from ASPNET. But you do need to spend more time on dotnet/installer to create the right layout.

Is that resolver specific to the built-in tools? I assumed it also played a role in global tools. If that's not the case, I'd be happy to do the extra legwork in the installer.

2021-03-25 22:42 UTC, wli3 commented
> Is that resolver specific to the built-in tools

That resolver is only for built-in tools. So dotnet-watch, dotnet-dev-cert, dotnet-user-secrets

2021-03-28 21:51 UTC, wli3 commented on src/Cli/dotnet/CommandFactory/CommandResolution/DotnetToolsCommandResolver.cs
> +    /// This includes <c>dotnet-watch</c>, <c>dotnet-dev-certs<c>, <c>dotnet-sql-cache<c>, and <c>dotnet-user-secrets</c>.
You need to always keep this list in sync whenever there is a change

2021-04-07 19:01 UTC, pranavkm commented
There's some co-ordination involved between the SDK and the installer to pull this off. I'll pick this up when I have a bit more time.

2021-04-07 19:01 UTC, closed without merging