Revert "Remove Hot Reload support from dotnet watch (#22217)"
dotnet/sdk pull request #22262
Opened 2021-10-22 04:03 UTC by 3nprob

This reverts #22217.

2021-10-22 07:09 UTC, 0rvar approved these changes
LGTM

2021-10-22 08:24 UTC, matkoch approved these changes
I approve. Lol :D

2021-10-22 09:26 UTC, damianh approved these changes

2021-10-22 09:36 UTC, wieslawsoltes approved these changes

2021-10-22 09:41 UTC, fjod approved these changes

2021-10-22 09:44 UTC, xb-bx approved these changes

2021-10-22 09:45 UTC, thefringeninja approved these changes

2021-10-22 09:47 UTC, jmacato approved these changes

2021-10-22 09:51 UTC, oskardudycz approved these changes

2021-10-22 10:01 UTC, yreynhout approved these changes

2021-10-22 10:15 UTC, jameswoodley approved these changes

2021-10-22 10:25 UTC, redsquare approved these changes
Looks good to go

2021-10-22 10:31 UTC, Happypig375 requested changes
I broke the approve chain!

2021-10-22 10:41 UTC, Kryptos-FR approved these changes

2021-10-22 10:52 UTC, slang25 approved these changes
Looks good to me 😃

2021-10-22 10:55 UTC, ghuntley approved these changes
Legend

2021-10-22 10:55 UTC, gkinsman approved these changes

2021-10-22 10:57 UTC, tetious approved these changes

2021-10-22 10:59 UTC, vtortola approved these changes

2021-10-22 10:59 UTC, adamralph approved these changes

2021-10-22 11:01 UTC, lombartec approved these changes

2021-10-22 11:01 UTC, jchannon approved these changes

2021-10-22 11:05 UTC, Elfocrash approved these changes

2021-10-22 11:13 UTC, danspark approved these changes

2021-10-22 11:17 UTC, stefan-schweiger approved these changes

2021-10-22 11:39 UTC, Xor-el approved these changes
Looks good to me. 🌝

2021-10-22 11:43 UTC, PiotrKarczmarz approved these changes
Love the open source spirit here ❤

2021-10-22 11:53 UTC, vchirikov approved these changes

2021-10-22 11:55 UTC, lulzzz approved these changes

2021-10-22 12:01 UTC, joshuapassos approved these changes
LGTM

2021-10-22 12:03 UTC, ghost approved these changes

2021-10-22 12:04 UTC, BSanchidrian approved these changes
Looks good to everyone apparently

2021-10-22 12:09 UTC, MrBliz approved these changes
No issues here, good to merge!

2021-10-22 12:17 UTC, serialseb approved these changes

2021-10-22 12:30 UTC, dgoemans approved these changes

2021-10-22 12:31 UTC, worldbeater approved these changes

2021-10-22 12:32 UTC, DiegoTobarra approved these changes
🚀

2021-10-22 12:34 UTC, SLAVONchick approved these changes

2021-10-22 12:38 UTC, Tyrrrz requested changes
Looks good, small comments

2021-10-22 12:39 UTC, lol768 approved these changes

2021-10-22 12:47 UTC, horsdal approved these changes

2021-10-22 12:51 UTC, lucaslra approved these changes

2021-10-22 12:52 UTC, rbeverly approved these changes
I endorse this request.

2021-10-22 12:56 UTC, ChaseFlorell approved these changes
LGTM 
![Clippy_ShipIt](https://user-images.githubusercontent.com/471626/138465772-fb03f333-af23-45ec-9aca-c118aa4832f0.gif)

2021-10-22 13:01 UTC, rude-seagull approved these changes

2021-10-22 13:04 UTC, nek0d3r approved these changes

2021-10-22 13:35 UTC, wiktor-golonka approved these changes

2021-10-22 13:44 UTC, luthus approved these changes

2021-10-22 13:46 UTC, GiampaoloGabba approved these changes

2021-10-22 13:52 UTC, sbatman approved these changes
Looking Good

2021-10-22 13:55 UTC, GeorgDangl approved these changes

2021-10-22 13:55 UTC, smohekey approved these changes

2021-10-22 13:56 UTC, mlibk approved these changes

2021-10-22 14:05 UTC, Aaronontheweb approved these changes
![Godspeed](https://media.giphy.com/media/edLKLYMlNFPJC/giphy.gif)

2021-10-22 14:12 UTC, ChrisH91 approved these changes

2021-10-22 14:16 UTC, dustinmoris approved these changes

2021-10-22 14:23 UTC, pkese approved these changes

2021-10-22 14:26 UTC, MisterJimson approved these changes

2021-10-22 14:32 UTC, Caelestian approved these changes

2021-10-22 14:37 UTC, Drabenstein approved these changes

2021-10-22 14:49 UTC, praeclarum approved these changes
This is a great feature to have in .net

2021-10-22 15:03 UTC, mlyle approved these changes

2021-10-22 15:06 UTC, enusbaum approved these changes
Approved! 😃

2021-10-22 15:07 UTC, SP2G50000 approved these changes

2021-10-22 15:15 UTC, ArminShoeibi approved these changes
Approved

2021-10-22 15:23 UTC, supertr0n approved these changes

2021-10-22 15:24 UTC, kblok approved these changes

2021-10-22 15:32 UTC, DaniilTymofieiev approved these changes

2021-10-22 15:37 UTC, mariano approved these changes
👊

2021-10-22 15:40 UTC, nikolalukovic approved these changes

2021-10-22 15:43 UTC, mael8 approved these changes

2021-10-22 15:45 UTC, fMichaleczek approved these changes

2021-10-22 15:55 UTC, TheCraftyMaker approved these changes

2021-10-22 16:09 UTC, ascott18 approved these changes

2021-10-22 16:10 UTC, misyltoad approved these changes

2021-10-22 16:13 UTC, MarcoMacedoP approved these changes
LGTM!

2021-10-22 16:14 UTC, mhmd-azeez approved these changes
lgtm

2021-10-22 16:17 UTC, andrewlock approved these changes

2021-10-22 16:17 UTC, adrianwright109 approved these changes
LGTM :shipit:

2021-10-22 16:22 UTC, atrauzzi approved these changes

2021-10-22 16:25 UTC, Redouane64 approved these changes
lgtm

2021-10-22 16:27 UTC, RehanSaeed approved these changes

2021-10-22 16:30 UTC, nozzlegear approved these changes

2021-10-22 16:32 UTC, tachyons approved these changes
I have no idea about what I am doing here, but here is my approval anyway

2021-10-22 16:34 UTC, adelarsq approved these changes

2021-10-22 16:35 UTC, VictorTomaili approved these changes
👍

2021-10-22 16:35 UTC, AndrewZu1337 approved these changes

2021-10-22 16:36 UTC, lrpe approved these changes

2021-10-22 16:51 UTC, TomaszRewak approved these changes

2021-10-22 16:57 UTC, JohnnyWombwell approved these changes

2021-10-22 16:58 UTC, Siddhant-K-code approved these changes

2021-10-22 17:08 UTC, thhous-msft approved these changes

2021-10-22 17:12 UTC, HaydnDias approved these changes

2021-10-22 17:14 UTC, Clawthorn approved these changes
I approve of this, because:

The fact that the original PR was submitted and then immediately locked so that no one could comment on it while it was being rushed through, means that you knew what you did was wrong, and did it anyway.

Any changes made to a community-driven project like this done in bad faith **_needs_** to be reverted, addressed, and then discussed heavily before it's ever considered again.

2021-10-22 17:25 UTC, Hellevar approved these changes

2021-10-22 17:26 UTC, Reintjuu approved these changes

2021-10-22 17:45 UTC, ma3yta approved these changes

2021-10-22 17:49 UTC, spixy approved these changes

2021-10-22 17:51 UTC, ptrstpp950 approved these changes
LGTM! 🙊🙉🙈

2021-10-22 17:59 UTC, henriqueu96 approved these changes

2021-10-22 18:09 UTC, jvyden approved these changes

2021-10-22 18:13 UTC, TimurZanagar approved these changes

2021-10-22 18:13 UTC, ghost approved these changes

2021-10-22 18:14 UTC, CyrusNajmabadi approved these changes

2021-10-22 18:34 UTC, MinZe25 approved these changes

2021-10-22 18:38 UTC, Anulo2 approved these changes

2021-10-22 18:47 UTC, ritasker approved these changes

2021-10-22 18:49 UTC, RandomSeeded approved these changes

2021-10-22 18:49 UTC, yordis approved these changes
lgtm

2021-10-22 18:54 UTC, ghost approved these changes

2021-10-22 19:08 UTC, madsoulswe approved these changes

2021-10-22 19:09 UTC, prajaybasu approved these changes

2021-10-22 19:17 UTC, jchen1 approved these changes

2021-10-22 19:38 UTC, ghost approved these changes

2021-10-22 19:56 UTC, renanrcp approved these changes

2021-10-22 19:58 UTC, dggmez approved these changes

2021-10-22 20:16 UTC, mletterle approved these changes

2021-10-22 20:22 UTC, d-abreu approved these changes

2021-10-22 20:33 UTC, maciej-izak approved these changes

2021-10-22 20:35 UTC, Je12emy approved these changes

2021-10-22 20:36 UTC, lucas-zimerman approved these changes

2021-10-22 20:39 UTC, khokho approved these changes

2021-10-22 20:45 UTC, kolpav approved these changes

2021-10-22 20:47 UTC, dszymon approved these changes

2021-10-22 20:50 UTC, ceifa approved these changes

2021-10-22 20:52 UTC, kkiwior approved these changes

2021-10-22 21:00 UTC, buddiman approved these changes

2021-10-22 21:11 UTC, edfarrow approved these changes

2021-10-22 21:13 UTC, LemongrabThree approved these changes

2021-10-22 21:21 UTC, vinevax approved these changes

2021-10-22 21:26 UTC, jpdillingham approved these changes

2021-10-22 21:42 UTC, paulirwin approved these changes

2021-10-22 21:46 UTC, GlebChili approved these changes

2021-10-22 21:47 UTC, romfir approved these changes

2021-10-22 21:49 UTC, Atulin approved these changes
LGTM, let's ship it like it's FedEx!
![image](https://user-images.githubusercontent.com/11233299/138526723-1401c17f-e6ce-450e-aa35-91ddf4175515.png)

2021-10-22 21:52 UTC, arminherling approved these changes

2021-10-22 21:53 UTC, rgwood approved these changes

2021-10-22 21:54 UTC, omaralbeik approved these changes

2021-10-22 21:58 UTC, xparadoxical approved these changes

2021-10-22 22:00 UTC, AraHaan reviewed
Why is hot reload needed for dotnet watch?

2021-10-22 22:05 UTC, Mercurial approved these changes
LETS FUCKING GO

2021-10-22 22:12 UTC, jouz3 approved these changes

2021-10-22 22:15 UTC, skel35 approved these changes

2021-10-22 22:19 UTC, AraHaan approved these changes

2021-10-22 22:20 UTC, alvarodl approved these changes

2021-10-22 22:23 UTC, kotylo approved these changes

2021-10-22 22:31 UTC, sandstreampop approved these changes
This might be a controversial stance - but I personally believe that fundamental .NET features, like Hot Reloading, should not be locked for the many users in the world that do not use Visual Studio.

LGTM

2021-10-22 22:33 UTC, byronbenitez approved these changes
LGTM

2021-10-22 22:42 UTC, asbjornu approved these changes

2021-10-22 22:46 UTC, Rarisma approved these changes

2021-10-22 22:52 UTC, jmarolf approved these changes

2021-10-22 22:57 UTC, BellaCoconuts approved these changes
LGTM

2021-10-22 23:02 UTC, DarryStonem approved these changes

2021-10-22 23:04 UTC, repsejnworb approved these changes

2021-10-22 23:04 UTC, dirien approved these changes
LGTM

2021-10-22 23:08 UTC, payambordbar approved these changes

2021-10-22 23:16 UTC, AlbertoMonteiro approved these changes

2021-10-22 23:32 UTC, gpproton approved these changes

2021-10-22 23:39 UTC, AnnaGuzy approved these changes

2021-10-22 23:44 UTC, Nuzair46 approved these changes

2021-10-22 23:51 UTC, Marusyk approved these changes

2021-10-22 23:55 UTC, ghost approved these changes

2021-10-22 23:59 UTC, 3052cole approved these changes
🐱‍👤

2021-10-23 00:03 UTC, GeeSuth approved these changes

2021-10-23 00:14 UTC, Drabenstein approved these changes

2021-10-23 00:18 UTC, 4oo4 approved these changes

2021-10-23 00:31 UTC, kamva9697 approved these changes

2021-10-23 00:46 UTC, seanat280 approved these changes

2021-10-23 01:06 UTC, zarlo approved these changes

2021-10-23 01:47 UTC, Cakery approved these changes

2021-10-23 01:54 UTC, ghost approved these changes

2021-10-23 02:06 UTC, nordfjord approved these changes

2021-10-23 02:36 UTC, EnceladusX2 approved these changes

2021-10-23 02:37 UTC, Oceanswave approved these changes

2021-10-23 02:57 UTC, thunder-coding approved these changes

2021-10-23 03:10 UTC, cybik approved these changes

2021-10-23 03:32 UTC, crozone approved these changes

2021-10-23 03:40 UTC, iceBear67 approved these changes

2021-10-23 03:41 UTC, EnsignPayton approved these changes

2021-10-23 03:42 UTC, qyl27 approved these changes

2021-10-23 03:44 UTC, albert-du approved these changes

2021-10-23 04:00 UTC, pavinan approved these changes

2021-10-23 04:20 UTC, nebulatgs approved these changes

2021-10-23 04:32 UTC, nvhoanganh approved these changes
LGTM

2021-10-23 05:19 UTC, hez2010 approved these changes
LGTM. If this doesn't get into .NET 6 GA, we will probably use RC2 for development forever until .NET 7 release. If @dotnet think the cli tool for hot reload is not ready, why not hide this feature behind a feature flag and allow users to opt-in instead of removing it completely?

2021-10-23 05:22 UTC, jwcone approved these changes
LGTM

2021-10-23 05:27 UTC, CallumMcLoughlin approved these changes

2021-10-23 05:45 UTC, igorsaux approved these changes

2021-10-23 05:54 UTC, SonicGD approved these changes

2021-10-23 06:04 UTC, jessedoyle approved these changes

2021-10-23 06:10 UTC, djhvscf approved these changes

2021-10-23 06:13 UTC, danielmarbach approved these changes
Looks good and important to me 🤘

2021-10-23 07:04 UTC, ilyalukyanov approved these changes

2021-10-23 07:11 UTC, igotinfected approved these changes

2021-10-23 07:13 UTC, srpeirce approved these changes

2021-10-23 07:23 UTC, clovisnicolas approved these changes

2021-10-23 07:44 UTC, SteveDunn approved these changes

2021-10-23 07:44 UTC, bartelink approved these changes

2021-10-23 07:46 UTC, KexyBiscuit approved these changes
Come on MSFT!

2021-10-23 07:48 UTC, maxekman approved these changes

2021-10-23 08:05 UTC, xmonader approved these changes

2021-10-23 08:07 UTC, DLC01 approved these changes

2021-10-23 08:21 UTC, shoooe approved these changes
LGTM

2021-10-23 08:24 UTC, ghuntley reviewed
> Just a week before we were going to have a meeting with .NET teams to talk about Unity's future with .NET... That's not a good signal sent for rebooting our partnership...
https://twitter.com/xoofx/status/1451780088815669249?s=21

2021-10-23 08:33 UTC, CumpsD approved these changes

2021-10-23 08:34 UTC, maxnatt approved these changes
LGTM

2021-10-23 08:36 UTC, matt-lethargic approved these changes

2021-10-23 08:36 UTC, lazyoracle approved these changes

2021-10-23 08:37 UTC, misiektg86 approved these changes

2021-10-23 08:42 UTC, MrLesk approved these changes

2021-10-23 08:43 UTC, Zxilly approved these changes

2021-10-23 08:45 UTC, Mrxx99 approved these changes

2021-10-23 08:59 UTC, ankitvijay approved these changes

2021-10-23 09:01 UTC, PizzaConsole approved these changes
Putting it back really is the right thing to do.

2021-10-23 09:03 UTC, arudei-dev approved these changes

2021-10-23 09:04 UTC, maartenba approved these changes

2021-10-23 09:09 UTC, Nobonex approved these changes

2021-10-23 09:15 UTC, oscyp approved these changes

2021-10-23 09:28 UTC, Whimfoome approved these changes

2021-10-23 09:36 UTC, Banyc approved these changes

2021-10-23 09:37 UTC, CoelacanthusHex approved these changes

2021-10-23 09:54 UTC, pgermishuys approved these changes

2021-10-23 09:55 UTC, aateeque approved these changes

2021-10-23 10:06 UTC, slanterns approved these changes
LGTM

2021-10-23 10:11 UTC, SecH0us3 approved these changes

2021-10-23 10:11 UTC, Sculas approved these changes

2021-10-23 10:19 UTC, mynetx approved these changes

2021-10-23 10:19 UTC, DominikBordzio approved these changes

2021-10-23 10:24 UTC, ArmaanMcleod approved these changes

2021-10-23 10:29 UTC, sdebruyn approved these changes

2021-10-23 10:33 UTC, Kazpers approved these changes
LGTM

2021-10-23 10:33 UTC, ghost approved these changes

2021-10-23 10:36 UTC, Artiume approved these changes

2021-10-23 10:38 UTC, goldyydev approved these changes

2021-10-23 10:39 UTC, Blind-Striker approved these changes

2021-10-23 10:43 UTC, shivamvinsol approved these changes

2021-10-23 10:51 UTC, BlackthornYugen approved these changes
Looks good

2021-10-23 10:54 UTC, Misaka13514 approved these changes

2021-10-23 10:57 UTC, vgist1 approved these changes

2021-10-23 11:12 UTC, Broderick890 approved these changes

2021-10-23 11:13 UTC, vadimalekseev approved these changes

2021-10-23 11:14 UTC, georgearnall approved these changes

2021-10-23 11:26 UTC, pavinduLakshan approved these changes

2021-10-23 11:31 UTC, christianscheer approved these changes

2021-10-23 11:32 UTC, AmritD approved these changes
LGTM!

2021-10-23 11:35 UTC, interpol-kun approved these changes
There is no reason to gatekeep the feature.

2021-10-23 11:36 UTC, NatoBoram approved these changes

2021-10-23 11:41 UTC, 0xced approved these changes

2021-10-23 11:56 UTC, bengelsdorff approved these changes

2021-10-23 12:27 UTC, Lundeful approved these changes

2021-10-23 12:31 UTC, Bortronx approved these changes

2021-10-23 12:31 UTC, aliveoutside approved these changes

2021-10-23 12:38 UTC, vlandemart approved these changes

2021-10-23 12:47 UTC, erenkulaksiz approved these changes

2021-10-23 12:48 UTC, george-petrakis approved these changes
LGTM

2021-10-23 13:00 UTC, isfot approved these changes

2021-10-23 13:12 UTC, sps014 approved these changes
LGTM

2021-10-23 13:15 UTC, Chicopower approved these changes

2021-10-23 13:26 UTC, Misaka13514 approved these changes

2021-10-23 13:27 UTC, MariuszKogut approved these changes

2021-10-23 13:28 UTC, cvertee approved these changes
[Org admin] Text has been removed due to a code of conduct violation.

2021-10-23 13:34 UTC, thiennn approved these changes

2021-10-23 13:39 UTC, RDIL approved these changes

2021-10-23 13:42 UTC, rem-coding approved these changes

2021-10-23 13:54 UTC, hamed880 approved these changes

2021-10-23 13:55 UTC, hamed880 approved these changes

2021-10-23 14:19 UTC, changetol8 approved these changes

2021-10-23 14:36 UTC, zverev-iv approved these changes

2021-10-23 14:36 UTC, hazevich approved these changes

2021-10-23 14:37 UTC, dczuo approved these changes

2021-10-23 14:38 UTC, nesherhh approved these changes

2021-10-23 14:42 UTC, blacksnake-rus approved these changes

2021-10-23 14:54 UTC, hangy approved these changes

2021-10-23 15:19 UTC, Joren-Thijs approved these changes

2021-10-23 15:25 UTC, rlizzo approved these changes

2021-10-23 15:26 UTC, seclerp approved these changes

2021-10-23 15:26 UTC, lentrodev approved these changes

2021-10-23 15:31 UTC, Scharkenberg approved these changes

2021-10-23 15:38 UTC, sigaloid approved these changes

2021-10-23 15:40 UTC, samokisha approved these changes

2021-10-23 15:55 UTC, Kableado approved these changes

2021-10-23 15:59 UTC, pkeogh approved these changes

2021-10-23 16:05 UTC, NickMaev approved these changes

2021-10-23 16:06 UTC, NickMaev approved these changes

2021-10-23 16:08 UTC, mikebrind approved these changes

2021-10-23 16:12 UTC, cbuffevant approved these changes

2021-10-23 16:18 UTC, Michielfx approved these changes

2021-10-23 16:18 UTC, U-C-S approved these changes

2021-10-23 16:18 UTC, fydar approved these changes

2021-10-23 16:21 UTC, dkmiller approved these changes

2021-10-23 16:27 UTC, mattimatt approved these changes

2021-10-23 16:28 UTC, ThomasPiskol approved these changes

2021-10-23 16:38 UTC, dylanbeattie approved these changes

2021-10-23 16:42 UTC, TimCorey approved these changes

2021-10-23 16:44 UTC, Reeceeboii approved these changes
Send it

2021-10-23 16:45 UTC, Cheeseless approved these changes

2021-10-23 16:47 UTC, jvstein approved these changes

2021-10-23 16:48 UTC, to11mtm approved these changes
We should consider adding a warning if Microsoft does not want this to be officially supported, but Aside from that LGTM.

2021-10-23 16:52 UTC, jpcrs approved these changes

2021-10-23 16:56 UTC, Rasie1 approved these changes

2021-10-23 17:03 UTC, leonardochaia approved these changes

2021-10-23 17:03 UTC, LauraWebdev approved these changes
LGTM

2021-10-23 17:06 UTC, Bilal-io approved these changes

2021-10-23 17:08 UTC, yhdgms1 approved these changes

2021-10-23 17:09 UTC, nor0x approved these changes

2021-10-23 17:15 UTC, gbraad approved these changes

2021-10-23 17:16 UTC, Jay-Madden approved these changes

2021-10-23 17:22 UTC, Hashimlokasher approved these changes

2021-10-23 17:23 UTC, GeeWizWow approved these changes

2021-10-23 17:24 UTC, jb-lopez approved these changes

2021-10-23 17:26 UTC, QuintenJ approved these changes

2021-10-23 17:26 UTC, infinitisno approved these changes

2021-10-23 17:33 UTC, MarekVigas approved these changes

2021-10-23 17:39 UTC, valikhan-k approved these changes
LGTM ✊

2021-10-23 17:47 UTC, OskarKlintrot approved these changes

2021-10-23 17:50 UTC, iczero approved these changes

2021-10-23 17:51 UTC, CommanderTvis approved these changes

2021-10-23 17:53 UTC, drakelord approved these changes

2021-10-23 17:55 UTC, thomhurst approved these changes

2021-10-23 17:59 UTC, darnley approved these changes

2021-10-23 18:02 UTC, myrup approved these changes

2021-10-23 18:05 UTC, nikolai-mb approved these changes

2021-10-23 18:05 UTC, Anessen97 approved these changes

2021-10-23 18:10 UTC, bennetfabian approved these changes

2021-10-23 18:10 UTC, rafaeldca approved these changes

2021-10-23 18:13 UTC, SilverCutePony approved these changes
Even ponies approve of these changes, merge them already!

2021-10-23 18:14 UTC, iammukeshm approved these changes

2021-10-23 18:14 UTC, gcurb approved these changes

2021-10-23 18:14 UTC, BlauFx approved these changes

2021-10-23 18:14 UTC, Smatify approved these changes

2021-10-23 18:18 UTC, KrisSiegel approved these changes

2021-10-23 18:19 UTC, controlhub approved these changes

2021-10-23 18:19 UTC, msdfib approved these changes

2021-10-23 18:20 UTC, ardacetinkaya approved these changes

2021-10-23 18:21 UTC, readonlyden approved these changes

2021-10-23 18:22 UTC, MarkAD88 approved these changes

2021-10-23 18:25 UTC, cschulzsuper approved these changes

2021-10-23 18:25 UTC, arihant2math approved these changes

2021-10-23 18:27 UTC, BitesizedLion approved these changes

2021-10-23 18:27 UTC, dresswithpockets approved these changes
LGTM (:

2021-10-23 18:27 UTC, wengh approved these changes

2021-10-23 18:31 UTC, davesearle approved these changes

2021-10-23 18:31 UTC, juanmuscaria approved these changes

2021-10-23 18:32 UTC, vcsjones approved these changes

2021-10-23 18:35 UTC, ahmeturun approved these changes

2021-10-23 18:35 UTC, hdimon approved these changes

2021-10-23 18:38 UTC, akiraveliara approved these changes

2021-10-23 18:42 UTC, eocampo approved these changes
LGTM

2021-10-23 18:45 UTC, attilaersek approved these changes

2021-10-23 18:47 UTC, studbolt approved these changes

2021-10-23 18:50 UTC, Cloudwalk9 approved these changes

2021-10-23 18:54 UTC, th0mk approved these changes

2021-10-23 18:54 UTC, d0pare approved these changes

2021-10-23 18:55 UTC, schui approved these changes

2021-10-23 18:56 UTC, gryffyn approved these changes

2021-10-23 18:57 UTC, Silverdark approved these changes

2021-10-23 18:57 UTC, mpedregalballesteros approved these changes
LGTM

2021-10-23 19:02 UTC, galvesribeiro approved these changes

2021-10-23 19:02 UTC, ekinbarut approved these changes

2021-10-23 19:03 UTC, ProKn1fe approved these changes

2021-10-23 19:03 UTC, BinarMorker approved these changes

2021-10-23 19:03 UTC, WolfSkin0 approved these changes

2021-10-23 19:03 UTC, theilgaz approved these changes

2021-10-23 19:04 UTC, zAfLu approved these changes

2021-10-23 19:06 UTC, joshcomley approved these changes

2021-10-23 19:08 UTC, rdurell approved these changes
LGTM

2021-10-23 19:09 UTC, dagstuan approved these changes

2021-10-23 19:11 UTC, jeromelaban approved these changes

2021-10-23 19:14 UTC, gorums approved these changes

2021-10-23 19:15 UTC, Q0 approved these changes

2021-10-23 19:16 UTC, Nepomuceno approved these changes

2021-10-23 19:29 UTC, microsec-bohdan approved these changes

2021-10-23 19:30 UTC, mgierlasinski approved these changes

2021-10-23 19:32 UTC, MaximCrabbe approved these changes

2021-10-23 19:32 UTC, MartinZikmund approved these changes

2021-10-23 19:42 UTC, odinnou approved these changes

2021-10-23 19:50 UTC, samamiller approved these changes
LGTM

2021-10-23 19:55 UTC, BartInTheField approved these changes

2021-10-23 20:01 UTC, Rohansi approved these changes

2021-10-23 20:03 UTC, jamesmckenzie approved these changes

2021-10-23 20:07 UTC, JoeStead approved these changes

2021-10-23 20:08 UTC, gildedero approved these changes

2021-10-23 20:10 UTC, cwe1ss approved these changes

2021-10-23 20:13 UTC, Dashell approved these changes

2021-10-23 20:16 UTC, Pomezny approved these changes

2021-10-23 20:20 UTC, caseyPav approved these changes

2021-10-23 20:21 UTC, jacksonisiah approved these changes

2021-10-23 20:23 UTC, rezonant approved these changes
Merge it or fork it, Microsoft

2021-10-23 20:24 UTC, beezz approved these changes

2021-10-23 20:28 UTC, Tanksteel approved these changes

2021-10-23 20:40 UTC, fooooooooooooooo approved these changes

2021-10-23 20:41 UTC, bschaatsbergen approved these changes
Ship it 🚢‼️

2021-10-23 20:47 UTC, rychai approved these changes

2021-10-23 20:49 UTC, DynamicField approved these changes

2021-10-23 20:51 UTC, tezjarl approved these changes

2021-10-23 20:53 UTC, jesperbjensen approved these changes

2021-10-23 20:56 UTC, SamuelBagattin approved these changes

2021-10-23 20:57 UTC, Krzysztof-Cieslak approved these changes

2021-10-23 20:57 UTC, ClumsyPenguin approved these changes

2021-10-23 20:59 UTC, alydemah approved these changes

2021-10-23 21:04 UTC, SilveIT approved these changes

2021-10-23 21:04 UTC, MrVitaly approved these changes
With ❤️ to OSS!

2021-10-23 21:06 UTC, redpulp approved these changes
LGTM

2021-10-23 21:07 UTC, JustinD85 approved these changes

2021-10-23 21:13 UTC, roeii approved these changes
LGTM

2021-10-23 21:13 UTC, ilyalukyanov approved these changes

2021-10-23 21:14 UTC, johannessorheim approved these changes

2021-10-23 21:14 UTC, merged

2021-10-23 21:26 UTC, dmitrymatin reviewed
LGTM

2021-10-23 21:30 UTC, sharms reviewed
Lgtm

2021-10-23 21:41 UTC, CodingKoopa reviewed
LGTM!

2021-10-23 21:51 UTC, abiudrn reviewed
LGTM!

2021-10-24 00:17 UTC, 4oo4 commented
@matkoniecz That makes zero sense, and seems like a misdirection from having to admit they made a bad business decision. It's unclear to me which source code they're referring to (dotnet or VC), but either way, wouldn't they be in version control?

This was not an accident related to source code, they locked the PR and knew exactly what they were doing and knew it would be unpopular.

Microsoft listened to us this time but based on that post they learned nothing. Good relations with Open Source communities means not making them be vigilant for such detrimental changes, and being transparent instead if sneaky.

They knew this would upset people, and should've solicited community input BEFORE doing it.

2021-10-24 00:45 UTC, SNDST00M commented
It's really annoying to get notifs on "Microsoft being <X> boogeyman". I think a better forum such as Reddit or Hackernews is more appropriate

2021-10-24 00:48 UTC, xshiiiidev commented
.NET to the Moon 🚀

2021-10-24 01:44 UTC, mythay commented
Good. 🚀 
Community should have community style.
Sponsor should not only see short term interest.

2021-10-24 01:52 UTC, robby commented
:ship: it

2021-10-24 02:29 UTC, Oceanswave commented
We're human, we make mistakes, but the explanation doesn't add up.

2021-10-24 10:07 UTC, championshuttler reviewed
SGTM  :D

2021-10-24 13:00 UTC, divyeshio reviewed
Supported!!

2021-10-24 13:57 UTC, pm4rcin reviewed
LGTM!
Everyone should remember that M$ is M$ and they do stupid or strange things many times like e.g. [here](https://github.com/microsoft/vscode/issues/87268) (and good things too) but luckily community is stronger than giga-corp because they are scared of bad PR. Have a good day! Long live FOSS dotnet! :)
PS. Thanks TimCorey for informing me since I'd probably never hear of that without him.

2021-10-24 14:36 UTC, MeguminSama approved these changes

2021-10-24 15:51 UTC, shameelfazul reviewed
The community has a voice!

2021-10-24 15:53 UTC, JerryKusenberger reviewed
Adding my support!

2021-10-24 16:34 UTC, aktas12 reviewed
Thanks!

2021-10-24 17:31 UTC, trolley813 reviewed
LGTM (one more time after all)

2021-10-24 18:09 UTC, jessety reviewed
I've been very excited about the open, cross-platform future of .Net- it's fantastic to see this come to the right resolution

2021-10-24 18:21 UTC, harperjohn reviewed
yes...

2021-10-25 00:22 UTC, AraHaan commented
We need to push for the .NET Foundation to be fully independent from any companies (except monetarily and maintaining wise) but without any ability to force their company plans onto the open source aspects of the .NET Platform (excluding Visual Studio Integrations or roslyn). Meaning once they add something to the .NET SDK, it should be owned by the .NET Foundation (and not Microsoft) and so then Microsoft cannot remove it without approval from the community and members of the foundation so that way they do not accidentally remove something that will have a lot of push back from both the community and the foundation members alike. Exceptions could include things like security based issues however where the old code must be replaced because of some sort of security flaw somewhere.

2021-10-25 03:23 UTC, yrshaikh reviewed
LGTM :)

2021-10-25 05:42 UTC, gmertes reviewed
Please include me in the screenshot.

Also LGTM 🥰

2021-10-25 08:51 UTC, oreze reviewed
.NET Foundation should be fully independent from Microsoft, and that`s a reason. LGTM

2021-10-25 10:40 UTC, KrystianLesniak reviewed
Essential and biggest change for .NET 6 SDK 👍

2021-10-25 23:57 UTC, deividfortuna commented
+1

2021-11-01 07:02 UTC, Seirdy commented
> We need to push for the .NET Foundation to be fully independent from any companies (except monetarily and maintaining wise) but without any ability to force their company plans onto the open source aspects of the .NET Platform (excluding Visual Studio Integrations or roslyn). Meaning once they add something to the .NET SDK, it should be owned by the .NET Foundation (and not Microsoft) and so then Microsoft cannot remove it without approval from the community and members of the foundation so that way they do not accidentally remove something that will have a lot of push back from both the community and the foundation members alike.

This alone is not enough. Developers shouldn't have to sign away copyright under the existing CLA: signing off on the DCO would be a much better alternative that can help minimize the damage of locking up previously free features. This is why I'm generally hesitant to contribute to any project that requires signing a CLA.

2021-11-01 10:09 UTC, AraHaan commented
I agree, however some people do not care if they sign off on their own copyright if all they care about is the project being able to continue on and be maintained even after their death. Besides any of us can be developing 1 second and die the next by some unknown cause.

2021-11-02 02:03 UTC, newpost reviewed
good job

2021-11-02 02:31 UTC, ghuntley commented
Hey folks,

Back in 2014, .NET was open-sourced. It’s now 2021, https://github.com/dotnet/core/issues/505 was opened in 2017. Last week the .NET SDK had code ripped out of it by a CVP to sell more Visual Studio licenses.

> "Product managers don't have the authority to yank something in a release candidate with a go-live license :)" - [Phillip Carter](https://news.ycombinator.com/item?id=28989077)

It's time to increase the heat and awareness of https://github.com/dotnet/core/issues/505 - the singular thing that stands in the way of .NET completing its transition to an open programming language.

Introducing https://isdotnetopen.com/

This Ballmeresq cold war with tooling vendors only harms the ecosystem. The more people who can use .NET and that are attracted to .NET the more Microsoft can sell Azure because there’s great attach rates and uplift between .NET folks and Azure.

> ".NET, Visual Studio, and Visual Studio Code are all expensive ad campaigns funded by Azure. .NET and Visual Studio have excellent attach rate to Azure" - [msft-throwaway](https://news.ycombinator.com/item?id=28990820)

Every marketing activity (omg lost count) Microsoft has done with .NET about rar rar rar “we are open-source” is fundamentally lipstick on a pig if there is no way to debug programs authored in the language. What use is an open-source programming language that can’t be debugged?

2021-11-02 20:47 UTC, atrauzzi commented
I'm definitely not getting back into Azure, but I will gladly use .NET on Google Cloud and I'm sure the growth and ubiquity of the ecosystem helps them all the same.

So yeah, a fully open source and independent .NET is essential.

2021-11-02 21:22 UTC, francofgp commented
> I'm definitely not getting back into Azure, but I will gladly use .NET on Google Cloud and I'm sure the growth and ubiquity of the ecosystem helps them all the same.
> 
> So yeah, a fully open source and independent .NET is essential.
> 
> (@ghuntley -- feel free to link to my [blog post](https://atrauzzi.github.io/its-time-for-net-to-leave-home))

Nice reading

2021-11-03 21:38 UTC, akaij reviewed
lgtm

2021-11-10 15:48 UTC, hughesjs commented
Top work getting this reverted guys, really was an own-goal from Microsoft here. This was somehow even worse than excluding Linux from MAUI and pretending its genuinely cross-platform. As excited as I am for .NET 6, this really has undone a lot of the confidence I was starting to get that Stallman era Linux is cancer Microsoft had truly changed...

2021-12-18 23:35 UTC, thepwrtank18 commented
This is usually how it starts. Big company takes away, big company gives back, big company gets applause.

And then after that loop, it starts becoming big company taking away, just without the giving back, but with the applause.

2023-09-30 11:03 UTC, SHEHEERALIZX commented
We want the hot reload

2026-08-01 23:32 UTC, gndr7nkhyd-uk commented on eng/Version.Details.xml
> +    </Dependency>
###$