Add conditional to not build net46 in sourcebuild
dotnet/sdk pull request #2309
Opened 2018-06-05 12:45 UTC by dseefeld

A recent commit https://github.com/dotnet/sdk/commit/b16a4889367f1706ba8b9a7bcb3663329acb94cc to enable x-plat net46 build causes the source-build build to fail for 2.1.

2018-06-05 16:08 UTC, eerhardt commented
/cc @nguerrera - who changed this recently:  https://github.com/dseefeld/sdk/commit/b16a4889367f1706ba8b9a7bcb3663329acb94cc#diff-83d1b9d720377aaf70c666e9e75befd6

2018-06-05 18:09 UTC, nguerrera commented
@weshaggard assured me this would work. The whole point of that commit was to get these binaries into source build.

2018-06-05 18:09 UTC, nguerrera requested changes
Waiting to understand why we can't use the reference assembly package in source build as promised.

2018-06-05 18:11 UTC, nguerrera commented
See https://github.com/dotnet/source-build/issues/125#issuecomment-389626323

We are using the same reference assembly packages as roslyn tools.

2018-06-05 19:09 UTC, eerhardt commented
FYI - @weshaggard is OOF.

@nguerrera - can you help me understand where `Microsoft.NETFramework.ReferenceAssemblies` is hosted?  I can't find it on nuget.org or on https://dotnet.myget.org/gallery/dotnet-core.  Maybe to fix source-build we just need to add a new feed URL?

2018-06-05 19:56 UTC, crummel commented
I think we'll also need to change MSBuild:
https://github.com/Microsoft/msbuild/blob/ac19036b0de4f1b58c3be76d51000df8db98560c/src/Directory.Build.props#L27
once we get the reference assemblies sorted out since SDK is referencing the MSBuild assemblies we produce.

2018-06-05 21:52 UTC, nguerrera commented
AFAICT, we get  Microsoft.NETFramework.ReferenceAssemblies from https://dotnet.myget.org/F/roslyn-tools/api/v3/index.json

2018-06-05 21:52 UTC, nguerrera commented
It was my understanding from dotnet/source-build#125 that others in source-build were already using this.

2018-06-05 22:29 UTC, crummel commented
I don't think anyone is now but I've got MSBuild building on its own with [these changes](https://github.com/Microsoft/msbuild/compare/vs15.7_sourcebuild...crummel:tryWithMoreFrameworks?expand=1).  I'm going to try something similar with SDK now that that reference is unblocked if that looks reasonable.

2018-06-05 23:07 UTC, nguerrera commented
@crummel, hmm that's a different package than the one from roslyn-tools. Wes specifically mentioned roslyn tools so I'm confused. But if we can get this building in source build with that, ok.

2018-06-05 23:08 UTC, nguerrera commented
I think it would be good if source build could use Microsoft.NETFramework.ReferenceAssemblies because that one is based on the proposal that we intend to ship and it handles setting things up for you (no need to muck with FrameworkPathOverride, etc.)

2018-06-07 00:49 UTC, weshaggard commented
Yes lets try to use Microsoft.NETFramework.ReferenceAssemblies and move it to the dotnet-core feed if we need to. I was pretty sure it was already being used as a pre-built but if it isn't then we can and should start doing so.

2018-06-07 00:51 UTC, closed without merging