Fix failure to load System.IO.Compression.ZipFile due to automatic binding redirect
dotnet/sdk pull request #2362
Opened 2018-06-25 21:51 UTC by dsplaisted

Fixes #2292

There is a bug with the unification table for .NET 4.7.1, and the [workaround](https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/623552-BCL%20Higher%20assembly%20versions%20that%204.0.0.0%20for%20System.IO.Compression.ZipFile%20cannot%20be%20loaded%20without%20a%20binding%20redirect.md) is to add the following binding redirect:

```xml
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.IO.Compression.ZipFile" publicKeyToken="b77a5c561934e089" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.0.3.0" newVersion="4.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

With the fix for #2221, this is getting overridden with an automatic binding redirect to version 4.0.3.0, which fails at runtime because it disables the unification table, and because the version of the runtime file is 4.0.0.0.

Since the suggested binding redirect is wrong in this case, this PR removes that suggested redirect after RAR suggests it.

2018-06-25 21:52 UTC, dsplaisted commented
@joperezr @AlexGhiondea @nguerrera for review

2018-06-25 23:25 UTC, joperezr requested changes
The changes to remove the .dll LGTM, but if @AlexGhiondea confirms that another valid solution is to ask people to remove the redirect, I much rather do that as oposed to having your custom `RemoveZipFileSuggestedRedirect` target.

2018-06-26 00:12 UTC, dsplaisted commented
@dotnet-bot test Windows_NT Release

2018-06-26 00:12 UTC, dsplaisted commented
@ericstj for review

2018-06-26 00:13 UTC, dsplaisted commented on src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets
> +          Condition="'$(_TargetFrameworkVersionWithoutV)' &gt;= '4.7.1'">
Per our discussion, I don't think that it is dangerous to remove the binding redirect for all frameworks above 4.7.1, as those frameworks should always have the assembly in the unification table, and thus the binding redirect should never be needed (nor correct).

2018-06-26 15:16 UTC, ericstj commented
Why are you adding a code fix for a bad side-effects of a workaround?  Just update the workaround so it accounts for the problem.

If you want to make a code-fix then the right fix is to make RAR more aware of the targeting pack's file list and not suggest redirects for things that are in the framework.

2018-06-29 21:25 UTC, dsplaisted commented
@dotnet-bot test Ubuntu14.04 Release

2018-07-05 17:53 UTC, nguerrera approved these changes
Very reluctantly signing off with minor comments. The special casing to workaround a workaround feels wrong, but after must discussion elsewhere, I agree it's the least bad option here.

2018-07-05 17:53 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets
> +  <Target Name="RemoveZipFileSuggestedRedirect"
Make this "private" with leading "_"

2018-07-05 17:53 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Extensions.Tasks/msbuildExtensions/Microsoft/Microsoft.NET.Build.Extensions/Microsoft.NET.Build.Extensions.NETFramework.targets
> +  <Target Name="RemoveZipFileSuggestedRedirect"
Please comment this. I know some poor souls are going to read this and wonder what it's about. This is bizarre enough that tests aren't enough convey "why" we're doing it.

2018-07-05 23:02 UTC, dsplaisted commented
@dotnet-bot test this please

2018-07-06 01:04 UTC, dsplaisted commented
@dotnet-bot test this please

2018-07-06 02:12 UTC, dsplaisted commented
@dotnet-bot test this please

2018-07-06 03:23 UTC, merged