Add 1x flag
dotnet/sdk pull request #2369
Opened 2018-06-28 17:24 UTC by wli3

2018-06-28 17:35 UTC, livarcocc commented on src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.NuGetOfflineCache.targets
> +    <RestoreAdditionalProjectFallbackFoldersExcludes Condition=" '$(_IsNETCore1x)' == 'true' and '$(DisableImplicit1xNuGetFallbackFolder)' != 'true' ">$(RestoreAdditionalProjectFallbackFoldersExclude
Seems good.

2018-06-28 17:36 UTC, livarcocc commented on src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
> +        public void I_can_disable_1_x_implicit_msbuild_nuget_config(string frameworks, string projectPrefix, bool shouldExecutePass)
Also seems good.

2018-06-28 17:36 UTC, livarcocc approved these changes

2018-06-28 19:22 UTC, JunTaoLuo requested changes

2018-06-28 20:47 UTC, livarcocc commented on src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.NuGetOfflineCache.targets
>      <RestoreAdditionalProjectSources Condition=" '$(_IsNETCore1x)' == 'true' ">$(RestoreAdditionalProjectSources);$(_NugetFallbackFolder)</RestoreAdditionalProjectSources>
You are right, this is what needs to change. My bad for not catching this.

2018-06-28 20:47 UTC, livarcocc commented on src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.NuGetOfflineCache.targets
> +    <RestoreAdditionalProjectFallbackFoldersExcludes Condition=" '$(_IsNETCore1x)' == 'true' and '$(DisableImplicit1xNuGetFallbackFolder)' != 'true' ">$(RestoreAdditionalProjectFallbackFoldersExclude
@JunTaoLuo you are right. I missed it when I originally reviewed this.

2018-06-28 20:48 UTC, livarcocc commented on src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
> +        public void I_can_disable_1_x_implicit_msbuild_nuget_config(string frameworks, string projectPrefix, bool shouldExecutePass)
Given that our implementation above was wrong and this test didn't catch this, I wonder if this coverage is right.

2018-06-28 20:51 UTC, wli3 commented on src/Tests/Microsoft.NET.Restore.Tests/GivenThatWeWantToRestoreProjectsUsingNuGetConfigProperties.cs
> +        public void I_can_disable_1_x_implicit_msbuild_nuget_config(string frameworks, string projectPrefix, bool shouldExecutePass)
well, it is failing

2018-06-28 21:44 UTC, JunTaoLuo reviewed
The implementation now looks correct but the tests are failing. Maybe the restore you expect to fail are passing because of caching or you didn't disable online sources (nuget, etc).

2018-06-28 21:49 UTC, wli3 commented
@JunTaoLuo I am trying to verify these tests cannot run locally... which apparently true. (all tests in the file are red in test explore) so sorry for the noise.

You can see the test above it, the disabling all NuGetFallbackFolder is doing the same thing to assert fail. Cached package may not be the problem. Let me keep digging

2018-06-29 02:06 UTC, wli3 commented
@JunTaoLuo you are right. I added extra code to avoid cache being used. It is good now?

2018-06-29 07:27 UTC, JunTaoLuo approved these changes
Yup looks good

2018-06-29 17:06 UTC, merged