Fix escaping function when argument ends with odd number of backslashes
dotnet/sdk pull request #23988
Opened 2022-02-17 10:17 UTC by Evangelink

Fixes #23970

2022-02-17 13:38 UTC, MarcoRossignoli commented on src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
> +        [InlineData("--results-directory", "///")]
nit: empty test and null test

2022-02-17 13:41 UTC, MarcoRossignoli approved these changes

2022-02-17 13:42 UTC, MarcoRossignoli reviewed
some comments

2022-02-17 16:29 UTC, Evangelink commented on src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
> +                result.StdOut.Should().Contain("Failed:     1");
I am now also testing that the specified directory exists and contains items.

2022-02-17 16:30 UTC, Evangelink commented on src/Tests/dotnet-test.Tests/TestCommandParserTests.cs
> +    public class TestCommandParserTests
@MarcoRossignoli I have added specific unit tests in addition to integration tests.

2022-02-17 17:37 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
> +            if (input == null)
```suggestion
            if (input is null)
```

2022-02-17 17:37 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs
> +                throw new ArgumentNullException(nameof(input));
throw or return null? 🤔

2022-02-17 17:38 UTC, MarcoRossignoli commented on src/Tests/dotnet-test.Tests/GivenDotnetTestBuildsAndRunsTestfromCsproj.cs
> +                result.StdOut.Should().Contain("Failed:     1");
great thx

2022-02-18 08:10 UTC, MarcoRossignoli commented
/azp run

2022-02-18 08:10 UTC, MarcoRossignoli approved these changes

2022-02-18 10:51 UTC, MarcoRossignoli commented
@Evangelink  it's failing in some distributions

2022-02-18 14:32 UTC, MarcoRossignoli requested changes
some tests are failing

2022-02-20 14:50 UTC, MarcoRossignoli commented
@Evangelink  pls feel free to fix this one once we're good with the implementation https://github.com/dotnet/sdk/blob/main/src/Cli/dotnet/commands/dotnet-test/TestCommandParser.cs#L69

2022-02-21 10:17 UTC, Evangelink commented
@KalleOlaviNiemitalo Thank you for your feedback on the ticket and here!

I have discussed with the team and we believe it's better to keep the "add quotes" solution because of the various paths that could be taken (depending for example if you pass a project/sln or dll/exe - the latter doesn't get through msbuild) so some escape/unescape sequences might not happen. We know that the process is complex and there are lots of jumps between escape/unescape but sadly we are not able to simplify this much without introducing potential breaking changes.

> Does MSBuild itself parse quotation marks, or are those parsed only by the CLR when it translates the Windows command-line string to an array of strings? If MSBuild does not parse them, then perhaps TestCommand.SurroundWithDoubleQuotes should be replaced with something that percent-encodes commas, semicolons, and other problematic characters for MSBuild. And the quotation-mark complexity would be in ArgumentEscaper only.

MSBuild is also doing specific parsing of the quotes. On the original PR, when trying to fix an issue with a comma not escaped, we considered doing an encoding of all the special characters or to use the quotes solution. It felt that the quotes was the easiest/more global solution. Again as said in the previous paragraph, there are different paths taken with different escaping/unescaping mechanism in place which is not the easiest to follow.

2022-02-21 19:05 UTC, MarcoRossignoli approved these changes

2022-02-21 19:05 UTC, merged