Fix overrides filename
dotnet/sdk pull request #2538
Opened 2018-09-18 08:43 UTC by KevinRansom

F# AtrributeInfo doesn't work correctly when compiled using visual studio, because the filename for the shim is incorrect.

This change fixes that.

Change also needs to go to release/2.2.1

2018-09-19 17:31 UTC, nguerrera commented
> Change also needs to go to release/2.2.1

That will happen automatically if approved for 2.1.5xx (15.9) and this is merged

2018-09-19 17:31 UTC, nguerrera approved these changes

2018-09-19 17:32 UTC, nguerrera commented
@Pilchie for approval for 2.1.500 / VS 15.9

@livarcocc FYI

@KevinRansom Hold on merging until we have "approved to merge" label

2018-09-19 17:47 UTC, Pilchie commented
Approved for 15.9 Preview *4* (P3 would require QB insertion right now)

2018-09-19 17:58 UTC, nguerrera commented
@livarcocc @Pilchie Should we be holding merges in case we need to insert something else for P3?

2018-09-19 17:58 UTC, nguerrera requested changes
Putting "request changes" for now until we're sure branch is open for 15.9 P4.

2018-09-19 18:04 UTC, livarcocc commented
@nguerrera, yes. Let's hold off until we can "open" the branch for P4.

2018-10-01 23:17 UTC, livarcocc commented
we should be good to merge this now.

2018-10-01 23:17 UTC, livarcocc commented
@dotnet-bot Test Ubuntu14.04 Debug

2018-10-05 21:54 UTC, nguerrera approved these changes

2018-10-05 21:55 UTC, merged