Consistently use PackagedShimOutputRootDirectory to set the path to generated shims
dotnet/sdk pull request #2561
Opened 2018-10-01 22:18 UTC by natemcmaster

Follow up to bug in https://github.com/dotnet/sdk/pull/2413

When PackagedShimOutputRootDirectory is set to a custom location, `dotnet pack` on a global tool project fails. E.g.

> C:\Users\namc\.dotnet\x64\sdk\2.2.100-preview2-009404\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Publish.targets(169,5): error MSB3030: Could not copy the file "bin\Debug\netcoreapp2.1\/shims/netcoreapp2.1\win-x86\cowsay.exe" because it was not found. [C:\Users\namc\AppData\Local\Temp\korebuild\nu2in0u1.af5\src\Simple.CliTool\Simple.CliTool.csproj]

2018-10-01 23:09 UTC, livarcocc approved these changes

2018-10-01 23:10 UTC, livarcocc commented
@natemcmaster if you are targeting 2.2, you will need to take this issue to shiproom for approval. Otherwise, just target master for 3.0.

2018-10-01 23:10 UTC, livarcocc requested changes
Marking as rejected until we figure out which vehicle this should ship in.

2018-10-01 23:17 UTC, natemcmaster commented
@livarcocc yes, this needs to target 2.2. https://github.com/dotnet/sdk/pull/2413 introduces a bug which tests didn't catch because the did not assert "dotnet pack" succeeds. I'll let you do the needful w.r.t shiproom approvals.

2018-10-02 18:06 UTC, wli3 approved these changes

2018-10-02 18:19 UTC, wli3 commented
#### Description
Fix when msbuild property PackagedShimOutputRootDirectory is set to a custom location, dotnet pack on a global tool project fails
#### Customer Impact
PackagedShimOutputRootDirectory allow customization of output path of global tools shims from 2.1.4xx. However, giving this regression, it will cause _dotnet pack_ to fail.
#### Regression?
Yes.
#### Risk
Low. The property PackagedShimOutputRootDirectory and shims generation are only used in dotnet pack global tools.

2018-10-02 18:31 UTC, jamshedd commented
Approved for 2.2

2018-10-02 18:32 UTC, livarcocc approved these changes

2018-10-02 18:32 UTC, natemcmaster commented
@dotnet-bot test OSX10.12 Debug 
@dotnet-bot test OSX10.12 Release
@dotnet-bot test Windows_NT Debug 

These appeared to fail due to network flakiness.

2018-10-02 19:55 UTC, wli3 commented
@dotnet-bot test OSX10.12 Debug

2018-10-02 20:39 UTC, merged