Improve the example with specified language when language option is given with invalid option
dotnet/sdk pull request #28135
Opened 2022-09-23 15:51 UTC by GangWang01

### Problem
- https://github.com/dotnet/templating/issues/4494
- When valid bool option and invalid option are given, exception was 
- Cli lacks unit tests for the option with invalid names

### Solution

- Specified language is added to the example when language option is given together with invalid option.
- Handle bool option in TemplateOptionResult for handling no template found
- Expand Cli unit tests.

### Checks:
- [x] Added unit tests
- [ ] Added `#nullable enable` to all the modified files [?](https://github.com/dotnet/templating/wiki/Contributing#coding-style)

2022-09-23 15:53 UTC, baronfel approved these changes
This looks awesome, and I'm very happy to see how easy it is to build command examples with the infrastructure the templating team has put in place. Nice work @GangWang01!

2022-09-27 14:08 UTC, vlada-shubina commented
Agreed to retarget to 7.0.2xx.

2022-10-04 11:30 UTC, vlada-shubina commented
Retargeted to 7.0.2xx

2022-10-04 11:35 UTC, vlada-shubina requested changes
Please review the possibility of having other types than `bool` and `string`.

2022-10-04 11:35 UTC, vlada-shubina commented on src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/InstantiateCommand.NoMatchHandling.cs
> +                reporter.WriteCommand(example);
It would be good to revert the order to be `dotnet new console --language F# -h` here.

2022-10-04 11:35 UTC, vlada-shubina commented on src/Cli/Microsoft.TemplateEngine.Cli/Commands/create/TemplateOptionResult.cs
> +                    option.Option.ValueType == typeof(bool) ? optionResult.GetValueOrDefault<bool>().ToString() : optionResult.GetValueOrDefault<string>());
does it make sense to make it more generic?
the type may also be `int`, though more rare.

```suggestion
             optionResult.GetValueOrDefault().ToString();
```

not sure if this overload still exists though

2022-10-10 03:07 UTC, GangWang01 commented
@JanKrivanek I accidently removed you from reviewers. Please take a look if you have time.

2022-10-10 20:39 UTC, vlada-shubina approved these changes
Looks good now, thank you for adding the tests!

2022-10-13 11:50 UTC, merged