[dotnet-new] Add inRoot option for AddProjectsToSolutionPostAction
dotnet/sdk pull request #28295
Opened 2022-10-02 03:25 UTC by levimatheri

For [dotnet-new issue #4178](https://github.com/dotnet/templating/issues/4178).
Adds `inRoot` argument which is passed to `dotnet sln add` as `--in-root`. 

cc @vlada-shubina

2022-10-03 12:41 UTC, vlada-shubina requested changes
Thank you for adding tests!

Just noticed different behavior in logic below - could you please check it?

Thank you

2022-10-04 03:28 UTC, levimatheri commented on src/Assets/TestPackages/dotnet-new/Microsoft.TemplateEngine.TestTemplates.csproj
> +    <None Remove="test_templates\PostActions\AddProjectToSolution\BasicInSolutionRoot\Program.cs" />
Removed

2022-10-04 03:28 UTC, levimatheri commented on src/Cli/dotnet/commands/dotnet-new/PostActions/DotnetSlnPostActionProcessor.cs
> +            return AddProjectsToSolution(nearestSlnFilesFound[0], projectFiles, solutionFolder, inRoot);
Added logic to handle this case

2022-10-04 12:12 UTC, vlada-shubina commented
@levimatheri thank you for your effort.
I retargeted to 7.0.2xx to get it included to 7.0.2xx, and added couple of tests and comments to localization.

@JanKrivanek  could you please take a final look? Thank you.

2022-10-04 12:13 UTC, vlada-shubina approved these changes

2022-10-17 12:24 UTC, JanKrivanek approved these changes
Looks good to me. Thank you for the contribution!

2022-10-17 12:24 UTC, merged