Don't add AOT package in restore for < net7
dotnet/sdk pull request #31201
Opened 2023-03-14 21:03 UTC by jtschuster

Fixes https://github.com/dotnet/sdk/issues/30814.

However, now it doesn't warn or error if trying to Publish with PublishAot=true for .Net 6. Instead, it will only trim the application, it won't run ilc.

2023-03-15 02:37 UTC, dsplaisted approved these changes

2023-03-15 17:01 UTC, sbomer reviewed
Could you check if the other publish scenarios have the same problem? I think you could get it with PublishReadyToRun (maybe you need to opt into crossgen2) on downlevel TFMs too.

2023-06-09 22:25 UTC, jtschuster commented
I forgot to follow up on the PR feedback and let this get stale. The issue was still present in preview 4, and this fix is still necessary. @sbomer @agocke Can you take another look?

2023-06-09 22:43 UTC, sbomer requested changes
Thanks for following up on this!

Looking at this a second time, I don't think adding a TFM condition to the task is a good idea. The source of truth for which TFMs are supported by the various scenarios (not just AOT) lives in https://github.com/dotnet/installer/blob/main/src/redist/targets/GenerateBundledVersions.targets, and `ProcessFrameworkReferences` is the current choke point that produces errors for all of these scenarios. I've been leaning on this to improve the error messages (see https://github.com/dotnet/sdk/pull/32943 and https://github.com/dotnet/sdk/pull/33041).

The current restore behavior (restoring for all TFMs) is by design per https://github.com/dotnet/sdk/issues/30814#issuecomment-1442418518, so if we're unhappy with this behavior I think we should be looking at a broader solution that changes the design.

2024-12-31 22:07 UTC, closed without merging