updated containers docs
dotnet/sdk pull request #31884
Opened 2023-04-19 17:48 UTC by vlada-shubina

Removed the docs after today's decision to keep docs in dotnet/sdk-container-builds

Note: had to keep release notes here as they are used when on packing the NuGet package.

2023-04-25 16:42 UTC, donJoseLuis requested changes

2023-04-25 16:42 UTC, donJoseLuis commented on src/Containers/README.md
> +If you would like to contribute by creating a pull request, please refer to [dotnet/sdk contributing guide](https://github.com/dotnet/sdk#how-do-i-engage-and-contribute). Ideally, prior starting the
by adding 'Area-Containers' how exactly?

2023-04-25 19:40 UTC, baronfel approved these changes
LGTM - minor grammar/rewordings to the README content

2023-04-25 19:40 UTC, baronfel commented on src/Containers/README.md
> +If you would like to contribute by creating a pull request, please refer to [dotnet/sdk contributing guide](https://github.com/dotnet/sdk#how-do-i-engage-and-contribute). Ideally, prior starting the
```suggestion
This folder contains the source code for the .NET SDK containers build tools (`Microsoft.NET.Build.Containers`).

Documentation for the tools is available in the [dotnet/sdk-containers-builds](https://github.com/dotnet/sdk-container-builds/tree/main/docs) repo.

If you encounter an issue with the container build tools or would like to submit a feature request, please use the [dotnet/sdk-containers-builds](https://github.com/dotnet/sdk-container-builds/issues/new) repo.

If you would like to contribute by creating a pull request, please refer to [dotnet/sdk contributing guide](https://github.com/dotnet/sdk#how-do-i-engage-and-contribute). Ideally, before starting the effort find a corresponding issue in the [dotnet/sdk-containers-builds](https://github.com/dotnet/sdk-container-builds/issues) repo and let us and others know in a comment. If you plan to address the problem that is not reflected in any issue, please create one. Consider helping us triage the pull request by adding the 'Area-Containers' label.
```

2023-04-26 14:55 UTC, donJoseLuis approved these changes

2023-04-28 15:19 UTC, merged