[draft][release/7.0.4xx] removed restriction on Publish SDK to allow publishing non-web project
dotnet/sdk pull request #32422
Opened 2023-05-10 17:02 UTC by vlada-shubina

2023-05-15 10:53 UTC, YuliiaKovalova approved these changes

2023-05-15 10:54 UTC, YuliiaKovalova approved these changes

2023-05-15 14:12 UTC, dsplaisted requested changes
I am not a fan of having two Sdks referenced in the Project element: `<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Publish.Sdk">`

Can we try to see if there's another way we can support the scenarios we need for Console projects?

cc @baronfel

2023-05-15 14:32 UTC, vlada-shubina commented
> I am not a fan of having two Sdks referenced in the Project element: `<Project Sdk="Microsoft.NET.Sdk;Microsoft.NET.Publish.Sdk">`
> 
> Can we try to see if there's another way we can support the scenarios we need for Console projects?
> 
> cc @baronfel

We plan to hide it behind property or potentially include it based on condition. This is first step and intention is to see if we can lift restriction to ASP.NET projects in Publish SDK.

2023-05-15 19:36 UTC, dsplaisted commented
> Correct - this is just enabling the Publish SDK to work when added to console projects _at all_. The final fix would be a conditionally-imported `<Sdk Include... />` element as a next step.

Will that work with evaluation ordering?  If you have a conditionally-imported `<Sdk Include.../>`, then you can't import the `Sdk.props` file before the project file is evaluated where it would normally be imported.

2023-12-18 18:45 UTC, baronfel commented
Closing this as we went a different direction entirely - pushing the container targets themselves into the base SDK.

2023-12-18 18:45 UTC, closed without merging