Containers/CreateNewImage: don't change the user to root when ContainerUser is empty.
dotnet/sdk pull request #32594
Opened 2023-05-17 08:24 UTC by tmds

When a rootless base image is used without specifying a ContainerUser, the image user was changed to User="". This causes the application image to run as the 'root' user.

@baronfel ptal.

2023-05-17 08:29 UTC, tmds commented
This doesn't affect the Microsoft rootless base images because the `ContainerUser` gets set here:

https://github.com/dotnet/sdk/blob/1e3e940c5663d3a6eb0f896c213e8fd202eab7fb/src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets#L107-L112

2023-05-17 08:38 UTC, tmds commented
> the Microsoft rootless base images

Correction: none of the Microsoft base images are rootless. The user is expected to add the `USER ` directive (like the sdk tooling is doing here).

2023-05-18 02:09 UTC, baronfel commented
Interesting - this makes sense to me. Can you think of a way to test? An end-to-end test with specific properties would let you load and check the manifest's User value.

2023-05-18 16:52 UTC, tmds commented
I'll look into adding a test for this next week.

2023-05-19 01:58 UTC, baronfel requested changes
Requesting changes so it doesn't get merged without a test :)

2023-05-22 14:03 UTC, tmds commented
@baronfel I've added a test that verifies `CreateNewImage` doesn't replace the rootless user from a base image. ptal.

2023-05-22 14:34 UTC, baronfel approved these changes
Thanks for adding a test to keep this green going forward :+1:

2023-05-22 15:33 UTC, merged