Add all projects to MSBuildAllProjects property
dotnet/sdk pull request #371
Opened 2016-11-09 16:31 UTC by dsplaisted

Fixes #277 

@nguerrera

2016-11-09 16:38 UTC, rainersigwald approved these changes

2016-11-09 16:57 UTC, nguerrera commented
Tests are failing. I seem to be reviewing a lot of PRs in that state. Are you running build.cmd before sending these out for review?

2016-11-09 17:01 UTC, nguerrera requested changes
Waiting for green run before reviewing.

2016-11-09 17:02 UTC, dsplaisted commented
> Tests are failing. I seem to be reviewing a lot of PRs in that state. Are you running build.cmd before sending these out for review?

I'm not sure I've always remembered to do so, but generally, yes.  These changes passed locally for me.

2016-11-09 17:36 UTC, nguerrera approved these changes

2016-11-09 17:36 UTC, nguerrera commented on test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
> +                //  TODO: Remove this when https://github.com/NuGet/Home/issues/3851 is fixed
File bug on SDK to represent the TODO and link to the blocking external issue.

2016-11-09 17:36 UTC, nguerrera commented on test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
> +
Ditto.

2016-11-10 22:47 UTC, dsplaisted commented on test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
> +                //  TODO: Remove this when https://github.com/NuGet/Home/issues/3851 is fixed
> File bug on SDK to represent the TODO and link to the blocking external issue.

To clarify, you mean file a bug in the SDK repo to remove the workaround in tests once the NuGet bug is fixed.  Correct?

2016-11-10 22:54 UTC, nguerrera commented on test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
> +                //  TODO: Remove this when https://github.com/NuGet/Home/issues/3851 is fixed
Correct

2016-11-10 23:11 UTC, dsplaisted commented on test/Microsoft.NET.Build.Tests/GivenThatWeWantToBuildALibrary.cs
> +                //  TODO: Remove this when https://github.com/NuGet/Home/issues/3851 is fixed
OK, filed #380 for this

2016-11-10 23:18 UTC, merged