Add TFM check for `Publish-Trimmed-ReadyToRun-SingleFile`
dotnet/sdk pull request #3766
Opened 2019-10-19 00:32 UTC by swaroop-sridhar

The options `PublishSingleFile`, `PublishReadyToRun`, and `PublishTrimmed` are only supported when targetting netcoreapp3.0 or later.

Trying to publish to a different target (say `.netcoreapp2.1`) today:
* `PublishSingleFile` fails with the `PlaceHolderNotFoundInAppHostException` generated by the `HostWriter`.
* `PublishReadyToRun` and `PublishTrimmed` silently fail to turn on, but the `publish` itself suceeds.

This change adds an explicit TFM check to generate error/warnings for non-conforming targets.

`PublishSingleFile`, `PublishReadyToRun`, and `PublishTrimmed` require the following conditions to be true:
* `TargetFramework` is `netcoreapp`
* `TargetFrameworkVersion` is at least `3.0`
* The app is an executable (`OutputType=exe`)

If any of the conditions fail:
* `PublishSingleFile` fails with an appropriate error
* `PublishReadyToRun` and `PublishTrimmed` issue warnings, but publish itself succeeds.
  This is because:
    * The restriction against `classlibs` / `netstandard` frameworks may be relaxed in future releases
    * The version check should ideally be a failure, but they are warnings for maximum compatibility with `3.0` release.

Fixes https://github.com/dotnet/sdk/issues/3728

2019-10-19 00:32 UTC, swaroop-sridhar commented
@nguerrera Please review

2019-10-19 00:32 UTC, swaroop-sridhar commented
CC: @livarcocc  requesting to merge into 3.1 branch.

2019-10-19 00:33 UTC, swaroop-sridhar commented
CC: @fadimounir @sbomer

2019-10-23 19:28 UTC, swaroop-sridhar commented
@nguerrera  the Ubuntu_16_04 leg fails in the Microsoft.NET.Pack.Tests or Microsoft.NET.Build.Tests, which is not likely to be related to the change.

@wli3  said that this test leg is failing intermittently. Can you please advise if this needs to be investigated any further? Thanks.

2019-10-29 00:20 UTC, nguerrera approved these changes
Looks good, but please hold from merging. There is a possibility of a 3.1 p2 respin and we should not take this in p2.

2019-10-29 00:21 UTC, nguerrera requested changes
Waiting for branch to open.

2019-10-29 00:22 UTC, nguerrera commented
@tmeschter There are string changes in here for 16.4 / 3.1.100 SDK, did the loc cutoff pass yet?

2019-10-29 14:47 UTC, tmeschter commented
The string change cut off for 16.4 was this past Saturday, 10/26.

At this point you have three options:

1. Hold the change for the next release.
2. Rework the change to avoid any string changes.
3. Get an exception to the localization requirements.

2019-10-30 22:06 UTC, livarcocc commented
Putting this in 3.1.200 seems fine to me. Particularly because the work seems to be done and we are only missing LOC, which will happen naturally for 3.1.200.

2019-11-11 17:38 UTC, wtgodbe commented
@livarcocc @nguerrera is this approved for GA?

2019-11-11 19:52 UTC, swaroop-sridhar commented
I agree with taking this for 3.1.200.

2020-01-10 23:34 UTC, swaroop-sridhar commented
Submitted the change to 3.1.2xx branch.
https://github.com/dotnet/sdk/pull/4154

2020-01-10 23:34 UTC, closed without merging