Trim trailing .git from sourcelink repo urls in container generation
dotnet/sdk pull request #39161
Opened 2024-03-03 05:14 UTC by baronfel

Fixes https://github.com/dotnet/sdk-container-builds/issues/540 by trimming .git from sourcelink-derived repo urls

2024-03-03 05:37 UTC, baronfel commented
We're not really worried about `git clone` here though?

2024-03-03 06:38 UTC, KalleOlaviNiemitalo requested changes

2024-03-03 17:04 UTC, baronfel commented on src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
> +      <ContainerLabel Condition="'$(ContainerGenerateLabelsImageSource)' == 'true' and '$(PrivateRepositoryUrl)' != ''" Include="org.opencontainers.image.source" Value="$(_TrimmedRepositoryUrl)" />
good spot on #1 - I'll adjust the conditions to ensure better consistency. For #2 I suppose what's happening is `we're using `TrimEnd(char[])`, which removes all instances of those characters from the end. Better to replace with a substring call I suppose, even though this is less clear on visual inspection.

2024-03-03 18:22 UTC, baronfel commented on src/Containers/packaging/build/Microsoft.NET.Build.Containers.targets
> +      <_TrimmedRepositoryUrl Condition="'$(RepositoryType)' == 'git' and '$(PrivateRepositoryUrl)' != '' and $(PrivateRepositoryUrl.EndsWith('.git'))">$(PrivateRepositoryUrl.Substring(0, $(PrivateRep
Great point - updated after doing some manual validation.

2024-03-05 03:44 UTC, baronfel commented
/azp run

2024-03-06 08:38 UTC, ladipro approved these changes
Since there seems to be some controversy about always considering the `.git` prefix trimmable, do you think it would be worth adding an opt-out property?

2024-03-06 15:59 UTC, baronfel commented
> Since there seems to be some controversy about always considering the `.git` prefix trimmable, do you think it would be worth adding an opt-out property?

Not really, no - this seems pretty self-evident for git repo server configuration, and users have a pretty clear workaround if that's the case. We can always revisit if it becomes a problem for folks.

2024-03-06 15:59 UTC, merged