Add SmokeTestsLicenseScanPath prop for LicenseScan Test
dotnet/sdk pull request #41143
Opened 2024-05-24 09:09 UTC by Winniexu01

Related to https://github.com/dotnet/source-build/issues/4420 and https://github.com/dotnet/sdk/pull/41124

The source-build License Scan tests were failing when there wasn't an SDK archive that had been produced and in the test no `SdkTarballPath` value provide. Add a condition to check if the test is `License Scan Tests`: '/p:SmokeTestsLicenseScanPath=/src/dotnet/src/roslyn-analyzers/'. If the value of `SmokeTestsLicenseScanPath` is null, then the test is determined not to be a License Scan Test then will continue to verify the `SdkTarballItem`.

2024-05-24 15:29 UTC, mthalman commented
@Winniexu01 - Can you provide a link to a build that is failing in this way? The license scan test shouldn't have any dependency on the SDK archive.

2024-05-27 07:43 UTC, Winniexu01 commented
Closes to https://github.com/dotnet/source-build/issues/4429 and here is the [Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2460726&view=logs&j=280a01c8-006d-5537-2980-fc0860fb6840&t=31e20fde-7b14-5a5b-1378-8c4aefb12cd9)

2024-05-27 14:25 UTC, ViktorHofer commented on src/SourceBuild/content/Directory.Build.targets
> +      <SdkTarballItem Condition="'$(SdkTarballPath)' != ''" Include="$(SdkTarballPath) and '$(SmokeTestsLicenseScanPath)' == ''" />
From a separation of concerns POV this doesn't look right. This target shouldn't know about tests or test properties. Can you please describe the overall issue in more detail?

2024-05-27 14:25 UTC, ViktorHofer requested changes
From a separation of concerns POV this doesn't look right. This target shouldn't know about tests or test properties. Can you please describe the overall issue in more detail?

2024-05-28 03:01 UTC, Winniexu01 commented
The tests were failed because 'SdkTarballItem' should be provided by setting "SdkTarballPath" parameter or getting the value from "$(ArtifactsAssetsDir)Sdk/**/$(SdkFilenamePrefix)*$(ArchiveExtension)".

However, in the souce-build license tests, the "SdkTarballPath" parameter is not provided and no file is generated under "$(ArtifactsAssetsDir)Sdk", so 'SdkTarballItem' will always equal '' and the test will always fail with "Didn't find an SDK archive".

So I have come up with three possible solutions for your reference:
1. Provide the test properties: `SmokeTestsLicenseScanPath`. This parameters is currently only defined for License Scan tests.
2. Provide a special properties for the License Scan tests to ensure this test skips checking the 'SdkTarballItem' value.
3. Set the "SdkTarballPath" parameter to a non-null value.

Without changing the current code structure, I chose the first solution. By the way, I made a mistake by adding the condition in the wrong place, but I have corrected it now.

2024-05-28 10:14 UTC, ViktorHofer commented
Thanks for providing more information and also thanks for filing the issue. This makes sense.

I just submitted https://github.com/dotnet/sdk/pull/41200 with an alternative approach which I find better as it keeps the separation of concerns. PTAL.

2024-05-28 12:56 UTC, closed without merging