Add back Microsoft.Dotnet.Sdk.Internal project
dotnet/sdk pull request #41154
Opened 2024-05-24 15:06 UTC by akoeplinger

This is used by a bunch of repos to pick up the latest SDK: https://github.com/search?q=org%3Adotnet+MicrosoftDotnetSdkInternal+-repo%3Adotnet%2Fdotnet&type=code

Add it back until we transition these repos onto another package.

2024-05-24 15:09 UTC, lewing approved these changes

2024-05-24 15:29 UTC, akoeplinger commented
/backport to release/9.0.1xx-preview5

2024-05-24 16:36 UTC, MiYanni requested changes
Wait, why are we adding this back? It was some kind of hacky workaround from 5 years ago in the dotnet/installer repo. I don't want this here. Can we spend time figuring out a proper solution instead of reapplying the duct tape?

CC @marcpopMSFT

2024-05-27 09:46 UTC, akoeplinger commented
Ok. I'll keep https://github.com/dotnet/sdk/issues/41156 to track updating the repos with the new package.

2024-05-27 09:46 UTC, closed without merging