[release/9.0.1xx-preview5] Revert linker to last known good for preview 5 release
dotnet/sdk pull request #41222
Opened 2024-05-29 05:25 UTC by jtschuster

The dependency update in https://github.com/dotnet/sdk/pull/41166 pulled in a trimmer version that fails Blazor AOT tests. If the fix can't make it in, we should revert to the last known good build of ILLink so that Blazor AOT scenarios aren't broken in preview 5.

2024-05-29 16:16 UTC, agocke requested changes

2024-05-29 16:16 UTC, agocke commented on eng/Version.Details.xml
>        <Sha>d89832aaf3616212c6ffa32ed1320f5117907056</Sha>
```suggestion
      <Sha>5c06e5d01fa0ea4122e7202cefb921a779f9843a</Sha>
```

2024-05-29 17:50 UTC, agocke approved these changes

2024-05-30 18:28 UTC, jtschuster commented
No longer needed as the backport made it in with https://github.com/dotnet/sdk/pull/41249.

2024-05-30 18:28 UTC, closed without merging