Ensure all template code files have UTF-8 BOM
dotnet/sdk pull request #41376
Opened 2024-06-04 12:36 UTC by bjornen77

Ensured that all template code files in the repository are marked as UTF-8 BOM.

Contributes to #39187

2024-06-04 12:54 UTC, sharwell commented
I am strongly in favor of this, but I'm not a code owner in this repository.

2024-06-04 12:54 UTC, sharwell approved these changes

2024-06-04 12:56 UTC, baronfel commented
We haven't yet decided that we will even take this approach to BOM usage. There is further discussion to be had.

2024-06-04 12:56 UTC, baronfel requested changes
Marking request changes to prevent merge

2024-06-04 13:36 UTC, bjornen77 commented
> We haven't yet decided that we will even take this approach to BOM usage. There is further discussion to be had.

I agree that it would be good to have some discussions and guidance regarding BOM usage.

This PR only makes the code file BOM usage consistent. Today all template code files already have BOM(except the two files changed in this PR)

2024-07-09 16:40 UTC, richlander commented
Why? I'm not in favor of this.

My position: https://github.com/dotnet/sdk/issues/39187

@GrabYourPitchforks

2024-07-09 20:05 UTC, bjornen77 commented
I think that the main reason to include the UTF-8 BOM is to make sure Visual Studio opens the file as a UTF8 file(with BOM). Otherwise it will by default choose another encoding for the template file. This could lead to issues if you develop and save your file using Visual Studio on Windows and then run you program on Linux.

If Visual Studio changes it default "guess" to UTF8 instead of current behavior, omitting the BOM would be fine.

For more information see:
https://github.com/dotnet/sdk/issues/39187#issuecomment-2147146329

2024-07-09 20:19 UTC, agocke commented
The C# compiler behavior is to always try parsing as UTF-8 first, then go to other encodings. I don’t know the VS behavior.

I’m generally against BOM. I think it’s generally _less_ portable than plain UTF-8. A lot of Unix tools don’t understand it.

2024-12-09 21:27 UTC, bjornen77 commented
Note that this PR only makes the SDK template files for C#, F#, and VB consistent regarding BOM usage. Currently, all C#, F#, and VB template files in the SDK include a BOM, except for two files. This PR fixes these two files and adds an editor config to ensure that future files also include a BOM, until a different decision is made.

I believe we should at least maintain consistency regarding BOM usage until we receive guidance or a decision on whether to include a BOM or not.

2024-12-09 23:30 UTC, richlander commented
Is there a VS issue filed on this? That would help.

I guess I'm not worried if we merge this PR or not since it doesn't change much.

2025-02-14 10:01 UTC, bjornen77 commented
@baronfel Is there anything else that needs to be done for this PR? Have you had a chance to discuss it yet?

Just a note that this PR ensures consistency in BOM usage across SDK template files for C#, F#, and VB. Currently, all template files include a BOM except for two, which this PR fixes. It also adds an editor config to maintain consistency going forward unless a different decision is made.

2025-09-30 04:30 UTC, closed without merging