Implement Channel Concept in dotnet test
dotnet/sdk pull request #42233
Opened 2024-07-18 08:35 UTC by mariam-abdulla

2024-07-18 12:17 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
> +                return;
now that's refactored this return won't exit `RunHelpAsync`

2024-07-18 12:18 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestApplication.cs
> +            if (isDll)
pls the {}

2024-07-18 12:18 UTC, mariam-abdulla commented
@baronfel @Forgind Please take a look at the PR and let us know if we may proceed to merge it.

2024-07-18 12:22 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
> +            _ = msBuildForwardingApp.Execute();
I think we should verify that the exit code is 0 or something went wrong inside the msbuild task...can you try to simulate a bug(throw Exception() inside the get task)?

If we failed here we should "print something and exit"

2024-07-18 12:23 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
> +        private TestApplication GenerateTestApplication(string modulePath)
we can inline this method and remove it it's doing a new

2024-07-18 12:23 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
> +        private void OnTestResultReceived(object sender, EventArgs args)
cleanup pls

2024-07-18 12:23 UTC, MarcoRossignoli approved these changes
some nit LGTM

2024-07-18 16:31 UTC, MarcoRossignoli approved these changes

2024-07-18 16:32 UTC, MarcoRossignoli commented on src/Cli/dotnet/commands/dotnet-test/TestingPlatformCommand.cs
> +                "-bl",
This should be removed or we will produce always the binlog

2024-07-18 16:32 UTC, MarcoRossignoli requested changes
One last change

2024-07-19 06:58 UTC, MarcoRossignoli approved these changes

2024-07-19 08:46 UTC, merged

2025-01-13 16:04 UTC, Evangelink commented
Relates to #45927