Add fantomas formatting support
dotnet/sdk pull request #44801
Opened 2024-11-11 22:08 UTC by jkone27

reference issue - https://github.com/dotnet/format/issues/1526

https://learn.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting

https://fsprojects.github.io/fantomas/

not clear how to test this, tried dogfood but is not working ?

2024-11-17 15:10 UTC, Smaug123 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +            var output = process.StandardOutput.ReadToEnd().ToLowerInvariant();
Better to use `_.Contains(_, StringComparison.OrdinalIgnoreCase)`?

2024-11-17 15:10 UTC, Smaug123 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +                Arguments = "tool list",
Shame they don't provide machine-readable output :(

2024-11-18 09:53 UTC, KalleOlaviNiemitalo requested changes
Potential deadlocks with RedirectStandardError, and missing handling for the `<PROJECT | SOLUTION>` argument.

2024-11-18 14:41 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +                RedirectStandardError = true,
shall we switch it off? or what's the best solution for this item?

2024-11-18 14:43 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +                Arguments = "fantomas .",
thanks for this review, how do i access the passed `[<PROJECT | SOLUTION>]` argument/path in this section of code?

2024-11-18 14:57 UTC, baronfel commented
One proposal I'd like to make is instead of calling `dotnet tool list --format json` you could use the tool list parsing code directly from the SDK. I'm not entirely sure what value there is in keeping format (and watch, but that's another discussion) outside of the main SDK command tree as a separate executable, and in the past we have had dependency problems due to the separation. @marcpopMSFT do you have opinions on merging the commands more deeply?

2024-11-18 15:56 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/Commands/RootFormatCommand.cs
> +                if (CodeFormatter.AnyFSharpFiles(Directory.GetCurrentDirectory()))
yes i think is possible, now i pass "." to it, if i will pass a valid path argument for the sln or proj, it should work, but what about individual .fsx script files, they are individual files, not part of any solution or project (stand alone) potentially

2024-11-18 16:22 UTC, jkone27 commented
@baronfel i think some stuff is internal atm, so cannot be accessed at this level (for example contracts for dotnet tool list), is there ways i can access tool list from here? is this store registered or available cross dotnet commands?

https://github.com/dotnet/sdk/blob/fc58e122239d2b640aac0584028dc820fee65b09/src/Cli/dotnet/ToolPackage/IToolPackageStoreQuery.cs#L10

2024-11-18 16:33 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/Commands/RootFormatCommand.cs
> +                        CodeFormatter.LogFantomasInstallationInstructions(logger);
actually many times F# and C# project can be mixed within a single solution, so i wouldnt report an hard error? C# code can still be formatted

2024-11-18 16:39 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/Commands/RootFormatCommand.cs
> +                if (CodeFormatter.AnyFSharpFiles(Directory.GetCurrentDirectory()))
i am passing now the general dotnet format project folder path, so i think should work in all cases, thanks!

2024-11-18 16:43 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +            logger.LogInformation("Fantomas tool is not installed. To install it, run the following commands:");
patched, thanks!

2024-11-18 16:43 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +                Arguments = "tool list",
using now dotnet too list local json, thanks

2024-11-18 16:49 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/CodeFormatter.cs
> +            logger.LogInformation(message);
updated helper message for fantomas installation instructions

2024-11-18 18:02 UTC, jkone27 commented
tried to add dotnet tool list but got `D is an invalid starting value`?

https://dev.azure.com/dnceng-public/cbb18261-c48f-4abb-8651-8cdcb5474649/_apis/build/builds/872392/logs/152

2024-11-19 16:30 UTC, jkone27 commented on src/BuiltInTools/dotnet-format/Commands/RootFormatCommand.cs
> +                        CodeFormatter.LogFantomasInstallationInstructions(logger);
yes then i should log warning instead of info, right?

2025-09-30 04:30 UTC, closed without merging