Add DefaultProjectTypeGuid property set to CPS Guid
dotnet/sdk pull request #583
Opened 2017-01-05 03:43 UTC by dsplaisted

Fixes #522

2017-01-05 03:44 UTC, dsplaisted commented
@jgoshi

2017-01-05 03:46 UTC, davkean commented
This has to be *all* project types not just those that reference the SDK.

2017-01-05 03:46 UTC, davkean requested changes
As above.

2017-01-05 03:47 UTC, davkean commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.props
> +    <DefaultProjectTypeGuid>{13B669BE-BB05-4DDF-9536-439F39A36129}</DefaultProjectTypeGuid>
This is the wrong GUID, we're opt'ing everyone into the C# one. We should make the same change for VB.

2017-01-05 04:15 UTC, dsplaisted commented
@davkean 

> This has to be *all* project types not just those that reference the SDK.

I don't understand.  This property is going in the SDK, we can't properties in non-SDK projects from here.  Per dotnet/cli#5131, the plan is for the CLI to evaluate to get the `ProjectTypeGuid` and `DefaultProjectTypeGuid` properties.  Non-SDK projects should have the `ProjectTypeGuid` in the project file itself, so that logic should work for both SDK and non-SDK projects.

> This is the wrong GUID, we're opt'ing everyone into the C# one. We should make the same change for VB.

What's the VB GUID?  And is the one I added the right one for C#?

2017-01-05 04:17 UTC, davkean commented
The fix is supposed to be in CSharp targets not the SDK. Not all C# projects have a project type guid - go create a WinForms application and notice it doesn't have one.

2017-01-05 04:22 UTC, dsplaisted commented
@davkean But we don't want to use the CPS Guid for WinForms projects in this release, right?  So it sounds like we need this defined in the CSharp / VB targets in MSBuild to specify the old project system Guids and then in the SDK to specify the CPS Guids.

2017-01-05 04:23 UTC, davkean commented
@dsplaisted Skype me, we can discuss - you're missing a bunch of context.

2017-01-25 23:03 UTC, srivatsn commented
Closing in favour of https://github.com/Microsoft/msbuild/pull/1607

2017-01-25 23:03 UTC, closed without merging