Update SDK projects to use MSBuild Sdk attribute, and hence the version of the Sdk that ships with the CLI or VS
dotnet/sdk pull request #659
Opened 2017-01-16 21:17 UTC by dsplaisted

In addition to cleaning our project files up and dogfooding a recent version of the SDK, this fixes the design-time build and hence intellisense in VS for me on the latest builds of VS.

2017-01-17 21:57 UTC, srivatsn commented
Let's switch this to master.

2017-01-18 01:51 UTC, dsplaisted commented
@dotnet-bot test Ubuntu14.04 Debug please

2017-01-18 01:52 UTC, dsplaisted commented
@dotnet-bot test Windows_NT Debug please

2017-01-19 00:56 UTC, natidea commented on src/Tasks/Microsoft.NET.Build.Tasks.UnitTests/Microsoft.NET.Build.Tasks.UnitTests.csproj
> +    <None Update="all.asset.types.portable.deps.json">
>Update [](start = 10, length = 6)

What does `Update` mean here?

2017-01-19 01:01 UTC, natidea commented on test/Microsoft.NET.TestFramework/Microsoft.NET.TestFramework.csproj
>      </PackageReference>
Can we make `Version` an attribute for some of these package references?

2017-01-19 01:01 UTC, natidea approved these changes

2017-01-24 05:40 UTC, nguerrera commented
This broke the signed build when I did it as part of the loc change that got reverted. Check that you're not getting default signassembly=false and do a test signed build pre merge.

2017-01-24 05:44 UTC, nguerrera requested changes
See above

2017-01-24 06:59 UTC, nguerrera commented
Also check that intermediate output path remains redirected.

2017-01-25 18:08 UTC, srivatsn approved these changes

2017-01-25 18:09 UTC, srivatsn commented
Once you verify the signed build, merge it in since it's an infrastructure change.

2017-01-25 18:55 UTC, nguerrera commented
Another thing was Jenkins builds failing often due to presumed arrival of #475 -- seems nobody is seeing that anymore (and it's closed due to that). Just make sure the CLI we use has recent bits.

2017-01-30 22:19 UTC, nguerrera commented
Discussed offline with Daniel. Closing as the same change is part of the loc change that needs to be reapplied and we don't want merge conflicts.

2017-01-30 22:19 UTC, closed without merging