Fix for Unit Test Template localization
dotnet/sdk pull request #709
Opened 2017-01-23 09:37 UTC by singhsarab

Fixing the name and description for the Unit Test template for .Net Core.
Consumed the localized strings from the package instead.

Validations:
Validated on the loc machine.
Screenshot with the fix:
![loc fix](https://cloud.githubusercontent.com/assets/18569990/22198625/5052aafc-e17d-11e6-93a2-0fa9b3378347.png)

2017-01-23 23:46 UTC, srivatsn requested changes
Please include xunit template localization as well.

2017-01-24 05:43 UTC, codito approved these changes

2017-01-25 14:41 UTC, sbaid commented
@srivatsn can u pl approve and merge this
Pl find ask mode template [Bug 371693](https://devdiv.visualstudio.com/DevDiv/_workitems?id=371693&_a=edit):[LOC] Name and description for .Net core templates are not localized.

2017-01-25 17:55 UTC, srivatsn approved these changes

2017-01-25 17:56 UTC, srivatsn commented
@MattGertz for RTM consideration -  template is in [Bug 371693](https://devdiv.visualstudio.com/DevDiv/_workitems?id=371693&_a=edit):[LOC] Name and description for .Net core templates are not localized..

2017-01-25 22:35 UTC, natidea commented
Approved to merge via [374631](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/374631)

2017-01-25 22:51 UTC, merged