Use case insensitive comparison when checking whether implicit package references are overridden
dotnet/sdk pull request #733
Opened 2017-01-26 06:53 UTC by dsplaisted

Fixes #679

2017-01-26 07:47 UTC, srivatsn approved these changes

2017-01-26 16:53 UTC, dsplaisted commented
@MattGertz for approval

#### Scenario

A user has a `PackageReference` in the project file for a package that is also implicitly added by the SDK, but they use a different capitalization (which is pretty likely to happen when editing project files manually, as the capitalization we use is `NETStandard.Library` and `Microsoft.NETCore.App`).  We are supposed to give them a warning telling them they don't need the explicit reference.  However, we currently don't show the warning if the capitalization doesn't match.  This fixes that.

#### Bug

#679

#### Workarounds

Be careful about capitalization of package IDs, or know via other means that we implicitly add package references for NETStandard.Library and Microsoft.NETCore.App.

#### Risk

Low

#### Performance Impact

Negligible. This adds a conversion to lowercase when checking for duplicate PackageReference items

#### Regression Analysis

Not a regression

2017-01-26 17:10 UTC, nguerrera requested changes
See above

2017-01-26 17:10 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/CheckForImplicitPackageReferenceOverrides.cs
> +            var duplicateItems = PackageReferenceItems.GroupBy(i => i.ItemSpec.ToLowerInvariant()).Where(g => g.Count() > 1);
Use the GroupBy overload that takes a comparer and pass StringComparer.OrdinalIgnoreCase

2017-01-26 18:19 UTC, MattGertz commented
@dsplaisted Can you clarify what the behavior is if we don't fix this?  Drilling into the associated issues, I see the "Crippling" log file reference, but I don't see how that translates to actual user experience.

2017-01-26 18:55 UTC, dsplaisted commented
@MattGertz If we don't fix dotnet/roslyn-project-system#1290, then the experience will be a message box will show in Visual Studio similar to https://github.com/dotnet/roslyn-project-system/issues/1290#issuecomment-275273940, but things should work mostly correctly after clicking OK.

If we do fix that bug, then I believe the result will be that the `PackageReference` in the project file will be silently ignored, which would be very confusing to users if they specified a different version than the implicit `PackageReference`.

2017-01-26 19:21 UTC, dsplaisted commented
@MattGertz Per [your comment](https://github.com/dotnet/roslyn-project-system/issues/1290#issuecomment-275479806) on the other issue, did you mean to mark this one as approved to bring to shiproom also?

2017-01-26 19:25 UTC, MattGertz commented
Yes, thanks, I forgot.

2017-01-26 19:36 UTC, 333fred commented
@MattGertz approved to merge, or pending shiproom?

2017-01-26 19:41 UTC, MattGertz commented
Thanks for catching.

2017-01-26 22:41 UTC, natidea commented
Approved to merge via [375369](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/375369)

2017-01-27 00:17 UTC, nguerrera approved these changes

2017-01-27 00:33 UTC, natidea approved these changes

2017-01-27 00:39 UTC, merged