Added osx to the pr job builders.
dotnet/sdk pull request #894
Opened 2017-02-21 21:15 UTC by 333fred

This adds OSX to the list of PR jobs so that we verify all commits on it.

2017-02-21 21:15 UTC, 333fred commented
@dotnet-bot test ci please

2017-02-22 16:00 UTC, nguerrera approved these changes

2017-02-25 03:07 UTC, nguerrera commented
Retarget to master after #917 goes in

2017-02-27 18:08 UTC, 333fred commented
@dotnet-bot test ci please

2017-02-27 18:54 UTC, nguerrera approved these changes

2017-02-27 23:45 UTC, livarcocc approved these changes

2017-03-06 22:26 UTC, dsplaisted commented
Are we waiting on anything to merge this? @333fred @nguerrera

2017-03-06 22:28 UTC, 333fred commented
It still doesn't work. See the offline mail thread.

2017-03-06 23:44 UTC, nguerrera requested changes
Preventing merge based on the fact that this isn't working (see above)

2017-03-07 00:34 UTC, 333fred commented
@dotnet-bot test ci please

2017-03-09 15:06 UTC, eerhardt commented
What's the status of this? We've introduced more "OSX" specific failures in the meantime: See #965

2017-03-09 18:12 UTC, 333fred commented
@dotnet-bot test ci please

2017-03-09 18:17 UTC, 333fred commented
Setting HOME appears to have made the build successful. @nguerrera, can you approve?

2017-03-09 18:22 UTC, 333fred commented
Test failures on OSX, appear to be the same ones in #965.

2017-03-09 18:37 UTC, nguerrera commented on build.sh
> +            ;;
@333fred I keep seeing unrelated whitespace cleanup. Is your editor configured to do that? It's not code review friendly.

2017-03-09 18:39 UTC, eerhardt commented
> Test failures on OSX, appear to be the same ones in #965.

Working on fixing them now.

2017-03-09 18:39 UTC, nguerrera commented on build.sh
> +    [ ! -d "$HOME" ] || rm -Rf $HOME
This line is terrifying. Do we really need to delete it? CI does a clean of the enlistment, right? And we don't put stuff in there.

2017-03-09 18:41 UTC, nguerrera commented on build.sh
> +# Some things depend on HOME and it may not be set. We should fix those things, but until then, we just patch a value in
This should say what things and link to bugs.

2017-03-09 18:42 UTC, nguerrera commented on netci.groovy
> +def osList = ['Windows_NT', 'Windows_NT_FullFramework', 'Ubuntu14.04', 'Ubuntu16.04', 'OSX']
Does this include 10.12?

2017-03-09 18:43 UTC, 333fred commented on netci.groovy
> +def osList = ['Windows_NT', 'Windows_NT_FullFramework', 'Ubuntu14.04', 'Ubuntu16.04', 'OSX']
Not sure, @mmitche? What OS is the OSX host?

2017-03-09 18:45 UTC, 333fred commented on build.sh
> +    [ ! -d "$HOME" ] || rm -Rf $HOME
I copied it from the CliCommandLineParser repo. @jonsequitur, was there a reasoning behind deleting everything?

2017-03-09 18:45 UTC, eerhardt commented on netci.groovy
> +def osList = ['Windows_NT', 'Windows_NT_FullFramework', 'Ubuntu14.04', 'Ubuntu16.04', 'OSX']
See https://github.com/dotnet/corefx/pull/16562/files for how corefx explicitly includes 10.12

2017-03-09 18:46 UTC, 333fred commented on build.sh
> +            ;;
Yes, my editor trims whitespace. Which works fine when I'm creating a file, but less fine when I'm not.

2017-03-09 19:04 UTC, nguerrera commented on build.sh
> +# NuGet depends on HOME and it may not be set. Until it's fixed, we just patch a value in
Bug filed?

2017-03-09 19:17 UTC, nguerrera approved these changes

2017-03-09 21:01 UTC, eerhardt commented on build.sh
> +    [ ! -d "$HOME" ] || rm -Rf $HOME
I have an extremely strong feeling that CliCommandLineParser just copied it from

https://github.com/dotnet/cli/blob/master/build.sh#L19-L25

which came in over a year ago here:
https://github.com/dotnet/cli/commit/34b0b688f7db70003514e0aefbee47868e6d5f71
with the commit message `patch up some final missing CI build things`

2017-03-09 21:06 UTC, eerhardt commented
test ci please

2017-03-09 21:19 UTC, eerhardt commented
@333fred - I'm getting errors on the OSX run with your latest changes:

https://ci.dot.net/job/dotnet_sdk/job/master/job/GenPRTest/job/release_osx10.12_prtest/1/console

```
13:09:16 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
13:09:16 Parameter name: path1
13:09:16    at System.IO.Path.Combine(String path1, String path2, String path3)
13:09:16    at NuGet.Common.NuGetEnvironment.GetFolderPath(SpecialFolder folder)
13:09:16    at NuGet.Common.NuGetEnvironment.GetFolderPath(NuGetFolderPath folder)
13:09:16    at NuGet.Configuration.SettingsUtility.GetHttpCacheFolder()
13:09:16    at NuGet.Configuration.NuGetPathContext.Create(ISettings settings)
13:09:16    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
13:09:16    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
13:09:16    at Microsoft.DotNet.Cli.Telemetry..ctor(INuGetCacheSentinel sentinel, String sessionId)
13:09:16    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
13:09:16    at Microsoft.DotNet.Cli.Program.Main(String[] args)
```

are the NuGet env vars set up correctly?

2017-03-09 22:00 UTC, eerhardt commented
@333fred @nguerrera - OSX.10.12 now passes:

https://ci.dot.net/job/dotnet_sdk/job/master/job/GenPRTest/job/release_osx10.12_prtest/3/

I'll let you guys merge when ready.

2017-03-09 22:03 UTC, merged