Changing Fx_version to more consistent RuntimeFrameworkVersion
dotnet/sdk pull request #964
Opened 2017-03-09 03:04 UTC by ramarag

Fix towards https://github.com/dotnet/sdk/issues/961

cc @eerhardt @nguerrera

2017-03-09 05:18 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +    Generates the project used to restore netcoreapp correspoding to RuntimeFrameworkVersion
typo: s/correspoding/corresponding/

2017-03-09 05:19 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
I don't see how this line does anything. It either does nothing when RuntimeFrameworkVErsion is empty or sets RuntimeFrameworkVersion to itself.

2017-03-09 05:19 UTC, nguerrera requested changes
See above

2017-03-09 05:19 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
Same for RuntimeIdentifier just above it.

2017-03-09 05:20 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
Ah never mind. I see this is CDATA for generating a project. Funky and easy to miss in a diff with only so much context.

2017-03-09 05:24 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
Wait, wouldn't the CDATA just write `$(RuntimeIdentifier)` expression and not its value and therefore generate a no-op after all. This is quite confusing.

2017-03-09 06:06 UTC, ramarag commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
it is part of CDATA, used to generate a csproj

2017-03-09 14:52 UTC, nguerrera commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
So the $(...) in CDATA is replaced with evaluated value? I see. The Condition is weird then. Can you remove it?

2017-03-11 03:46 UTC, ramarag commented on src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.CrossGen.targets
> +      <RuntimeFrameworkVersion Condition="'$(RuntimeFrameworkVersion)' != ''">$(RuntimeFrameworkVersion)</RuntimeFrameworkVersion>
done

2017-03-11 06:51 UTC, nguerrera approved these changes

2017-03-13 15:18 UTC, eerhardt approved these changes

2017-03-13 22:17 UTC, ramarag commented
@dotnet-bot  test Ubuntu16.04

2017-03-13 22:18 UTC, ramarag commented
@dotnet-bot  test Ubuntu16.04 Debug

2017-03-13 22:39 UTC, ramarag commented
@dotnet-bot test Ubuntu16.04 Release

2017-03-14 00:34 UTC, merged