Allow skip and configuration of install dirs
dotnet/sdk pull request #976
Opened 2017-03-10 23:16 UTC by karajas

2017-03-11 05:53 UTC, nguerrera commented on build.ps1
> +dotnet msbuild /t:restore /p:RestorePackagesPath=$PackagesPath $RepoRoot\sdk-templates.sln /verbosity:$Verbosity
Why did you change this?

2017-03-11 05:55 UTC, nguerrera commented on build.ps1
> +dotnet msbuild /t:restore /p:RestorePackagesPath=$PackagesPath $RepoRoot\sdk-templates.sln /verbosity:$Verbosity
This was done and reverted before. It broke signed builds, but I don't recall why. These are windows-only builds. I am pushing to have them moved to a different repo.

2017-03-11 05:55 UTC, nguerrera commented on build.ps1
> +dotnet msbuild /t:restore /p:RestorePackagesPath=$PackagesPath $RepoRoot\sdk-templates.sln /verbosity:$Verbosity
cc @srivatsn who may recall exactly what broke

2017-03-11 06:39 UTC, nguerrera requested changes
See above

2017-05-04 06:20 UTC, nguerrera commented
@karajas Do you still need this?

2017-05-04 16:41 UTC, karajas commented
At the moment, I have a workaround in the source build repo. Though I'd like to clean this up and check it in. I'll try to get to this within the next few days

2017-05-25 19:34 UTC, nguerrera commented
@karajas I'm going to close this since there hasn't been activity in a while. Feel free to re-open or start another PR when you're ready to pick it back up.

2017-05-25 19:34 UTC, closed without merging